/* Generated by french/build_french.js from the JSON files in french/. Do not edit by hand. */
window.FRENCH = {
 "vocab": {
  "language": "fr",
  "dialect": "modern standard",
  "source": "Modern standard French. Verb forms that are tabulated are taken from Le Conjugueur (lefigaro.fr), the Bescherelle-style tables, read 2026-10-09. Articles and pronouns are taken from Lawless French (lawlessfrench.com), read 2026-10-09. Beau and vieux are taken from Larousse, read 2026-10-09. French nouns have no genitive and no declension number, so those Greek fields are not used. The parallel fields are plural, gender, and article.",
  "nouns": [
   {
    "lemma": "roi",
    "plural": "rois",
    "gender": "m",
    "article": "le",
    "gloss": "king",
    "ref": "Larousse, s.v. roi, nom masculin, larousse.fr/dictionnaires/francais/roi/69725, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "femme",
    "plural": "femmes",
    "gender": "f",
    "article": "la",
    "gloss": "woman",
    "ref": "Larousse, s.v. femme, nom féminin, larousse.fr/dictionnaires/francais/femme/33217, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "homme",
    "plural": "hommes",
    "gender": "m",
    "article": "l’",
    "gloss": "man",
    "note": "The definite article elides: l’homme, not le homme.",
    "ref": "Larousse, s.v. homme, nom masculin, larousse.fr/dictionnaires/francais/homme/40240, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "cheval",
    "plural": "chevaux",
    "gender": "m",
    "article": "le",
    "gloss": "horse",
    "note": "The plural is chevaux. A plural chevals is not a French form.",
    "ref": "Larousse, s.v. cheval, chevaux, nom masculin, larousse.fr/dictionnaires/francais/cheval/15173, read 2026-10-09. Larousse, s.v. pluriel, gives chevaux as the plural of cheval. Larousse junior, s.v. cheval, prints Au pluriel: des chevaux."
   },
   {
    "lemma": "ville",
    "plural": "villes",
    "gender": "f",
    "article": "la",
    "gloss": "city",
    "ref": "Larousse, s.v. ville, nom féminin, larousse.fr/dictionnaires/francais/ville/82000, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "mer",
    "plural": "mers",
    "gender": "f",
    "article": "la",
    "gloss": "sea",
    "note": "This is the sea. Larousse lists maire and mère as homonyms, and those are other words.",
    "ref": "Larousse, s.v. mer, nom féminin, larousse.fr/dictionnaires/francais/mer/50562, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "livre",
    "plural": "livres",
    "gender": "m",
    "article": "le",
    "gloss": "book",
    "note": "This is the book, Larousse livre 1, nom masculin. The feminine livre is the pound, and it is another word. Livres is also a form of the verb livrer, which is not in this set.",
    "ref": "Larousse, s.v. livre, nom masculin, assemblage de feuilles, larousse.fr/dictionnaires/francais/livre/47531, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "maison",
    "plural": "maisons",
    "gender": "f",
    "article": "la",
    "gloss": "house",
    "ref": "Larousse, s.v. maison, nom féminin, larousse.fr/dictionnaires/francais/maison/48725, read 2026-10-09. Larousse, s.v. féminin, names maison among feminine nouns for things. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "ami",
    "plural": "amis",
    "gender": "m",
    "article": "l’",
    "gloss": "friend",
    "feminine": "amie",
    "feminine_plural": "amies",
    "note": "The headword is ami, amie. The article elides before the vowel.",
    "ref": "Larousse, Dictionnaire de français, s.v. ami, amie, read 2026-10-09. The headword prints both genders. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "cadeau",
    "plural": "cadeaux",
    "gender": "m",
    "article": "le",
    "gloss": "gift",
    "note": "A noun in -eau takes -x in the plural: cadeaux.",
    "ref": "Larousse junior, s.v. cadeau, nom masculin, Au pluriel: des cadeaux, larousse.fr/dictionnaires/junior/cadeau/2550, read 2026-10-09. Larousse, s.v. pluriel, names x as a written plural mark."
   },
   {
    "lemma": "route",
    "plural": "routes",
    "gender": "f",
    "article": "la",
    "gloss": "road",
    "ref": "Gender feminine and plural routes. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "jour",
    "plural": "jours",
    "gender": "m",
    "article": "le",
    "gloss": "day",
    "ref": "Gender masculine and plural jours. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "table",
    "plural": "tables",
    "gender": "f",
    "article": "la",
    "gloss": "table",
    "ref": "Larousse, s.v. féminin, names table among feminine nouns for things, larousse.fr/dictionnaires/francais/féminin/33208, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel). The own entry for table was not opened."
   },
   {
    "lemma": "jardin",
    "plural": "jardins",
    "gender": "m",
    "article": "le",
    "gloss": "garden",
    "ref": "Gender masculine and plural jardins. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   },
   {
    "lemma": "victoire",
    "plural": "victoires",
    "gender": "f",
    "article": "la",
    "gloss": "victory",
    "ref": "Larousse, s.v. victoire, nom féminin, larousse.fr/dictionnaires/francais/victoire/81858, read 2026-10-10. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel)."
   }
  ],
  "verbs": [
   {
    "lemma": "être",
    "gloss": "be",
    "kind": "irregular",
    "auxiliary": "avoir",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "avoir",
    "gloss": "have",
    "kind": "irregular",
    "auxiliary": "avoir",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "parler",
    "gloss": "speak",
    "kind": "regular -er, first group",
    "auxiliary": "avoir",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "finir",
    "gloss": "finish",
    "kind": "regular -ir, second group",
    "auxiliary": "avoir",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "vendre",
    "gloss": "sell",
    "kind": "regular -re, third group",
    "auxiliary": "avoir",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "aller",
    "gloss": "go",
    "kind": "irregular, third group",
    "auxiliary": "être",
    "tabulated": true,
    "note": "Aller ends in -er and is not in the first group. Le Conjugueur gives three stems: va- in the present, ir- in the future, all- elsewhere.",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "faire",
    "gloss": "do, make",
    "kind": "irregular, third group",
    "auxiliary": "avoir",
    "tabulated": true,
    "note": "The second person plural of the present is faites, and the first person plural is faisons.",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "venir",
    "gloss": "come",
    "kind": "irregular, third group",
    "auxiliary": "être",
    "tabulated": true,
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09"
   },
   {
    "lemma": "voir",
    "gloss": "see",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "prendre",
    "gloss": "take",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "dire",
    "gloss": "say",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "pouvoir",
    "gloss": "be able",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "vouloir",
    "gloss": "wish, want",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "savoir",
    "gloss": "know",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   },
   {
    "lemma": "écrire",
    "gloss": "write",
    "kind": "irregular, third group",
    "tabulated": false,
    "note": "Finite forms are not entered. No item asks for one.",
    "ref": "Lemma only. Le Conjugueur, lefigaro.fr, read 2026-10-09 was not opened for this verb."
   }
  ],
  "adjectives": [
   {
    "lemma": "bon",
    "feminine": "bonne",
    "gloss": "good",
    "class": "regular, with nn in the feminine",
    "note": "The feminine is bonne, bonnes. The masculine plural is bons. The n is doubled in the feminine. No compared form is asked.",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass."
   },
   {
    "lemma": "petit",
    "feminine": "petite",
    "gloss": "small",
    "class": "regular",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass."
   },
   {
    "lemma": "grand",
    "feminine": "grande",
    "gloss": "great, tall",
    "class": "regular",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass."
   },
   {
    "lemma": "beau",
    "feminine": "belle",
    "gloss": "beautiful",
    "class": "masculine singular bel before a vowel or a mute h",
    "ref": "Larousse, Dictionnaire de français, s.v. beau and s.v. vieux, larousse.fr, read 2026-10-09 Laura K. Lawless, Lawless French, Irregular adjectives, lawlessfrench.com/grammar/irregular-adjectives/, read 2026-10-09",
    "note": "Lawless prints beau, bel, belle, beaux, belles, and says the special masculine form is required before a masculine singular noun that begins with a vowel or a mute h. There is no special plural. Larousse says the same for bel."
   },
   {
    "lemma": "vieux",
    "feminine": "vieille",
    "gloss": "old",
    "class": "masculine singular vieil before a vowel or a mute h",
    "ref": "Larousse, Dictionnaire de français, s.v. beau and s.v. vieux, larousse.fr, read 2026-10-09 Laura K. Lawless, Lawless French, Irregular adjectives, lawlessfrench.com/grammar/irregular-adjectives/, read 2026-10-09",
    "note": "Lawless prints vieux, vieil, vieille, vieux, vieilles, with the example un vieil homme, and says there is no special plural, as in trois vieux hommes. Larousse says vieil is used before a masculine singular noun that begins with a vowel or a mute h. A literary sentence sometimes keeps vieux before a vowel. The form asked here is vieil."
   },
   {
    "lemma": "heureux",
    "feminine": "heureuse",
    "gloss": "happy",
    "class": "regular -eux, feminine -euse",
    "ref": "Larousse, s.v. heureux, heureuse, adjectif, larousse.fr/dictionnaires/francais/heureux/39846, read 2026-10-09. Lawless, Agreement, says an adjective agrees in gender and number."
   }
  ],
  "other": [
   {
    "lemma": "dans",
    "pos": "preposition",
    "gloss": "in, into",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "avec",
    "pos": "preposition",
    "gloss": "with",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "pour",
    "pos": "preposition",
    "gloss": "for",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "sans",
    "pos": "preposition",
    "gloss": "without",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "à",
    "pos": "preposition",
    "gloss": "to, at",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "de",
    "pos": "preposition",
    "gloss": "of, from",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   },
   {
    "lemma": "et",
    "pos": "conjunction",
    "gloss": "and",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "mais",
    "pos": "conjunction",
    "gloss": "but",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "bien",
    "pos": "adverb",
    "gloss": "well",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "souvent",
    "pos": "adverb",
    "gloss": "often",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "hélas",
    "pos": "interjection",
    "gloss": "alas",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "ah",
    "pos": "interjection",
    "gloss": "ah",
    "ref": "Ordinary function word of standard French."
   },
   {
    "lemma": "ce",
    "pos": "pronoun",
    "gloss": "this, that",
    "note": "With est, the vowel drops: c’est. After c’est the pronoun is the stressed form.",
    "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09"
   }
  ]
 },
 "paradigms": {
  "language": "fr",
  "dialect": "modern standard",
  "source": "Articles: Laura K. Lawless, Lawless French, Articles, Definite articles, and Partitive article, lawlessfrench.com, read 2026-10-09. Pronouns: Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09. Beau and vieux: Larousse, Dictionnaire de français, s.v. beau and s.v. vieux, larousse.fr, read 2026-10-09. Verbs: Le Conjugueur, lefigaro.fr, read 2026-10-09, indicative present, passé composé, imparfait, futur simple, and subjonctif présent only. The passé simple, the imperfect subjunctive, the conditional, and the imperative are printed on those pages and are not entered, except where a note has to say that a stored spelling is shared with one of them. Le Robert, Dico en ligne, « Subjonctif », dictionnaire.lerobert.com, read 2026-10-09 gives the regular subjunctive endings -e, -es, -e, -ions, -iez, -ent, and the exceptions avoir and être.",
  "article": {
   "lemma": "le, la, les",
   "gloss": "the; a; some",
   "ref": "Laura K. Lawless, Lawless French, Articles, Definite articles, and Partitive article, lawlessfrench.com, read 2026-10-09",
   "note": "The definite article agrees in gender and number. Le and la become l’ before a vowel or a mute h. À contracts with le and les, and de contracts with le and les. À la, à l’, de la, and de l’ do not contract. Du is both the masculine partitive and the contraction of de + le. Des is the indefinite plural, the partitive plural, and the contraction of de + les. The school rule reduces des to de before a preceding adjective in the plural, and usage also keeps des. That choice is not asked. In a negative sentence the indefinite and the partitive usually become de. That choice is not asked either.",
   "forms": {
    "definite": {
     "m_sg": "le",
     "f_sg": "la",
     "vowel": "l’",
     "pl": "les"
    },
    "indefinite": {
     "m_sg": "un",
     "f_sg": "une",
     "pl": "des"
    },
    "partitive": {
     "m_sg": "du",
     "f_sg": "de la",
     "vowel": "de l’",
     "pl": "des"
    },
    "contraction": {
     "au": "à + le",
     "aux": "à + les",
     "à la": "à + la",
     "à l’": "à + l’",
     "du": "de + le",
     "des": "de + les",
     "de la": "de + la",
     "de l’": "de + l’"
    }
   }
  },
  "nouns": [
   {
    "lemma": "roi",
    "ref": "Larousse, s.v. roi, nom masculin, larousse.fr/dictionnaires/francais/roi/69725, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "roi",
     "pl": "rois"
    }
   },
   {
    "lemma": "femme",
    "ref": "Larousse, s.v. femme, nom féminin, larousse.fr/dictionnaires/francais/femme/33217, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "femme",
     "pl": "femmes"
    }
   },
   {
    "lemma": "homme",
    "ref": "Larousse, s.v. homme, nom masculin, larousse.fr/dictionnaires/francais/homme/40240, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "homme",
     "pl": "hommes"
    }
   },
   {
    "lemma": "cheval",
    "ref": "Larousse, s.v. cheval, chevaux, nom masculin, larousse.fr/dictionnaires/francais/cheval/15173, read 2026-10-09. Larousse, s.v. pluriel, gives chevaux as the plural of cheval. Larousse junior, s.v. cheval, prints Au pluriel: des chevaux.",
    "forms": {
     "sg": "cheval",
     "pl": "chevaux"
    }
   },
   {
    "lemma": "ville",
    "ref": "Larousse, s.v. ville, nom féminin, larousse.fr/dictionnaires/francais/ville/82000, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "ville",
     "pl": "villes"
    }
   },
   {
    "lemma": "mer",
    "ref": "Larousse, s.v. mer, nom féminin, larousse.fr/dictionnaires/francais/mer/50562, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "mer",
     "pl": "mers"
    }
   },
   {
    "lemma": "livre",
    "ref": "Larousse, s.v. livre, nom masculin, assemblage de feuilles, larousse.fr/dictionnaires/francais/livre/47531, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "livre",
     "pl": "livres"
    }
   },
   {
    "lemma": "maison",
    "ref": "Larousse, s.v. maison, nom féminin, larousse.fr/dictionnaires/francais/maison/48725, read 2026-10-09. Larousse, s.v. féminin, names maison among feminine nouns for things. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "maison",
     "pl": "maisons"
    }
   },
   {
    "lemma": "ami",
    "ref": "Larousse, Dictionnaire de français, s.v. ami, amie, read 2026-10-09. The headword prints both genders. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "ami",
     "pl": "amis",
     "f_sg": "amie",
     "f_pl": "amies"
    },
    "note": "The feminine is formed like an adjective ending."
   },
   {
    "lemma": "cadeau",
    "ref": "Larousse junior, s.v. cadeau, nom masculin, Au pluriel: des cadeaux, larousse.fr/dictionnaires/junior/cadeau/2550, read 2026-10-09. Larousse, s.v. pluriel, names x as a written plural mark.",
    "forms": {
     "sg": "cadeau",
     "pl": "cadeaux"
    }
   },
   {
    "lemma": "route",
    "ref": "Gender feminine and plural routes. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "route",
     "pl": "routes"
    }
   },
   {
    "lemma": "jour",
    "ref": "Gender masculine and plural jours. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "jour",
     "pl": "jours"
    }
   },
   {
    "lemma": "table",
    "ref": "Larousse, s.v. féminin, names table among feminine nouns for things, larousse.fr/dictionnaires/francais/féminin/33208, read 2026-10-09. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel). The own entry for table was not opened.",
    "forms": {
     "sg": "table",
     "pl": "tables"
    }
   },
   {
    "lemma": "jardin",
    "ref": "Gender masculine and plural jardins. The own Larousse entry was not opened in this pass. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "jardin",
     "pl": "jardins"
    }
   },
   {
    "lemma": "victoire",
    "ref": "Larousse, s.v. victoire, nom féminin, larousse.fr/dictionnaires/francais/victoire/81858, read 2026-10-10. The plural mark s is the ordinary written plural (Larousse, s.v. pluriel).",
    "forms": {
     "sg": "victoire",
     "pl": "victoires"
    }
   }
  ],
  "adjectives": [
   {
    "lemma": "bon",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass.",
    "forms": {
     "m_sg": "bon",
     "f_sg": "bonne",
     "m_pl": "bons",
     "f_pl": "bonnes"
    },
    "note": "The feminine is bonne, bonnes. The masculine plural is bons. The n is doubled in the feminine. No compared form is asked."
   },
   {
    "lemma": "petit",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass.",
    "forms": {
     "m_sg": "petit",
     "f_sg": "petite",
     "m_pl": "petits",
     "f_pl": "petites"
    },
    "note": "Four forms. No case."
   },
   {
    "lemma": "grand",
    "ref": "Laura K. Lawless, Lawless French, Agreement, lawlessfrench.com/grammar/agreement/, read 2026-10-09 The four forms are the ordinary ones. The own Larousse entry for this adjective was not opened in this pass.",
    "forms": {
     "m_sg": "grand",
     "f_sg": "grande",
     "m_pl": "grands",
     "f_pl": "grandes"
    },
    "note": "Four forms. No case."
   },
   {
    "lemma": "beau",
    "ref": "Larousse, Dictionnaire de français, s.v. beau and s.v. vieux, larousse.fr, read 2026-10-09 Laura K. Lawless, Lawless French, Irregular adjectives, lawlessfrench.com/grammar/irregular-adjectives/, read 2026-10-09",
    "forms": {
     "m_sg": "beau",
     "m_sg_vowel": "bel",
     "f_sg": "belle",
     "m_pl": "beaux",
     "f_pl": "belles"
    },
    "note": "Lawless prints beau, bel, belle, beaux, belles, and says the special masculine form is required before a masculine singular noun that begins with a vowel or a mute h. There is no special plural. Larousse says the same for bel."
   },
   {
    "lemma": "vieux",
    "ref": "Larousse, Dictionnaire de français, s.v. beau and s.v. vieux, larousse.fr, read 2026-10-09 Laura K. Lawless, Lawless French, Irregular adjectives, lawlessfrench.com/grammar/irregular-adjectives/, read 2026-10-09",
    "forms": {
     "m_sg": "vieux",
     "m_sg_vowel": "vieil",
     "f_sg": "vieille",
     "m_pl": "vieux",
     "f_pl": "vieilles"
    },
    "note": "Lawless prints vieux, vieil, vieille, vieux, vieilles, with the example un vieil homme, and says there is no special plural, as in trois vieux hommes. Larousse says vieil is used before a masculine singular noun that begins with a vowel or a mute h. A literary sentence sometimes keeps vieux before a vowel. The form asked here is vieil."
   },
   {
    "lemma": "heureux",
    "ref": "Larousse, s.v. heureux, heureuse, adjectif, larousse.fr/dictionnaires/francais/heureux/39846, read 2026-10-09. Lawless, Agreement, says an adjective agrees in gender and number.",
    "forms": {
     "m_sg": "heureux",
     "f_sg": "heureuse",
     "m_pl": "heureux",
     "f_pl": "heureuses"
    },
    "note": "Four forms. No case."
   }
  ],
  "pronouns": {
   "ref": "Laura K. Lawless, Lawless French, Subject pronouns, Direct objects, Indirect objects, and Stressed pronouns, lawlessfrench.com, read 2026-10-09",
   "note": "Me, te, le, and la elide before a vowel or a mute h: m’, t’, l’. Lui as an indirect object is masculine or feminine. Lui as a stressed pronoun is masculine, and the feminine stressed form is elle. Nous and vous have one spelling for the subject, the direct object, the indirect object, and the stressed form, so the place shows the use. The reflexive series is me, te, se, nous, vous, se. It is not asked. Y and en are not in this table.",
   "subject": {
    "1s": "je",
    "2s": "tu",
    "3s_m": "il",
    "3s_f": "elle",
    "3s_indef": "on",
    "1p": "nous",
    "2p": "vous",
    "3p_m": "ils",
    "3p_f": "elles"
   },
   "direct_object": {
    "1s": "me",
    "2s": "te",
    "3s_m": "le",
    "3s_f": "la",
    "3s_vowel": "l’",
    "1p": "nous",
    "2p": "vous",
    "3p": "les"
   },
   "indirect_object": {
    "1s": "me",
    "2s": "te",
    "3s": "lui",
    "1p": "nous",
    "2p": "vous",
    "3p": "leur"
   },
   "stressed": {
    "1s": "moi",
    "2s": "toi",
    "3s_m": "lui",
    "3s_f": "elle",
    "3s_indef": "soi",
    "1p": "nous",
    "2p": "vous",
    "3p_m": "eux",
    "3p_f": "elles"
   },
   "reflexive": {
    "1s": "me",
    "2s": "te",
    "3s": "se",
    "1p": "nous",
    "2p": "vous",
    "3p": "se"
   }
  },
  "verbs": [
   {
    "lemma": "être",
    "gloss": "be",
    "kind": "irregular",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "Être takes avoir in the passé composé. Le Conjugueur prints the participle été four times, with no feminine ending. The future stem is ser-. Je serai is future. Je serais is conditional and is not entered.",
    "present": {
     "1s": "suis",
     "2s": "es",
     "3s": "est",
     "1p": "sommes",
     "2p": "êtes",
     "3p": "sont"
    },
    "passe_compose": {
     "1s": "ai été",
     "2s": "as été",
     "3s": "a été",
     "1p": "avons été",
     "2p": "avez été",
     "3p": "ont été"
    },
    "imparfait": {
     "1s": "étais",
     "2s": "étais",
     "3s": "était",
     "1p": "étions",
     "2p": "étiez",
     "3p": "étaient"
    },
    "futur": {
     "1s": "serai",
     "2s": "seras",
     "3s": "sera",
     "1p": "serons",
     "2p": "serez",
     "3p": "seront"
    },
    "subjonctif": {
     "1s": "sois",
     "2s": "sois",
     "3s": "soit",
     "1p": "soyons",
     "2p": "soyez",
     "3p": "soient"
    },
    "participe_present": "étant",
    "participe_passe": {
     "m_sg": "été",
     "f_sg": "été",
     "m_pl": "été",
     "f_pl": "été"
    }
   },
   {
    "lemma": "avoir",
    "gloss": "have",
    "kind": "irregular",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "The passé composé cells are the forms with no agreement, which is the agreement with the subject. The participle eu takes e and s when it agrees with a preceding direct object. Those agreeing forms are stored under participe_passe and are not asked. The future stem is aur-.",
    "present": {
     "1s": "ai",
     "2s": "as",
     "3s": "a",
     "1p": "avons",
     "2p": "avez",
     "3p": "ont"
    },
    "passe_compose": {
     "1s": "ai eu",
     "2s": "as eu",
     "3s": "a eu",
     "1p": "avons eu",
     "2p": "avez eu",
     "3p": "ont eu"
    },
    "imparfait": {
     "1s": "avais",
     "2s": "avais",
     "3s": "avait",
     "1p": "avions",
     "2p": "aviez",
     "3p": "avaient"
    },
    "futur": {
     "1s": "aurai",
     "2s": "auras",
     "3s": "aura",
     "1p": "aurons",
     "2p": "aurez",
     "3p": "auront"
    },
    "subjonctif": {
     "1s": "aie",
     "2s": "aies",
     "3s": "ait",
     "1p": "ayons",
     "2p": "ayez",
     "3p": "aient"
    },
    "participe_present": "ayant",
    "participe_passe": {
     "m_sg": "eu",
     "f_sg": "eue",
     "m_pl": "eus",
     "f_pl": "eues"
    }
   },
   {
    "lemma": "parler",
    "gloss": "speak",
    "kind": "regular -er, first group",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "Le Conjugueur calls this the general pattern of verbs in -er. The auxiliary is avoir, so the passé composé does not agree with the subject. For an -er verb, the singular and the third person plural of the present subjunctive are spelled like the present indicative, and the nous and vous forms are spelled like the imparfait. The clause shows which is meant. Le Robert, Dico en ligne, « Subjonctif », dictionnaire.lerobert.com, read 2026-10-09",
    "present": {
     "1s": "parle",
     "2s": "parles",
     "3s": "parle",
     "1p": "parlons",
     "2p": "parlez",
     "3p": "parlent"
    },
    "passe_compose": {
     "1s": "ai parlé",
     "2s": "as parlé",
     "3s": "a parlé",
     "1p": "avons parlé",
     "2p": "avez parlé",
     "3p": "ont parlé"
    },
    "imparfait": {
     "1s": "parlais",
     "2s": "parlais",
     "3s": "parlait",
     "1p": "parlions",
     "2p": "parliez",
     "3p": "parlaient"
    },
    "futur": {
     "1s": "parlerai",
     "2s": "parleras",
     "3s": "parlera",
     "1p": "parlerons",
     "2p": "parlerez",
     "3p": "parleront"
    },
    "subjonctif": {
     "1s": "parle",
     "2s": "parles",
     "3s": "parle",
     "1p": "parlions",
     "2p": "parliez",
     "3p": "parlent"
    },
    "participe_present": "parlant",
    "participe_passe": {
     "m_sg": "parlé",
     "f_sg": "parlée",
     "m_pl": "parlés",
     "f_pl": "parlées"
    }
   },
   {
    "lemma": "finir",
    "gloss": "finish",
    "kind": "regular -ir, second group",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "Le Conjugueur: verbs in -ir that form the present participle in -issant. The nous and vous forms of the imparfait and of the present subjunctive are spelled alike. The present and the present subjunctive also share finissent. The imperfect subjunctive, which is not entered, spells que je finisse like the present subjunctive.",
    "present": {
     "1s": "finis",
     "2s": "finis",
     "3s": "finit",
     "1p": "finissons",
     "2p": "finissez",
     "3p": "finissent"
    },
    "passe_compose": {
     "1s": "ai fini",
     "2s": "as fini",
     "3s": "a fini",
     "1p": "avons fini",
     "2p": "avez fini",
     "3p": "ont fini"
    },
    "imparfait": {
     "1s": "finissais",
     "2s": "finissais",
     "3s": "finissait",
     "1p": "finissions",
     "2p": "finissiez",
     "3p": "finissaient"
    },
    "futur": {
     "1s": "finirai",
     "2s": "finiras",
     "3s": "finira",
     "1p": "finirons",
     "2p": "finirez",
     "3p": "finiront"
    },
    "subjonctif": {
     "1s": "finisse",
     "2s": "finisses",
     "3s": "finisse",
     "1p": "finissions",
     "2p": "finissiez",
     "3p": "finissent"
    },
    "participe_present": "finissant",
    "participe_passe": {
     "m_sg": "fini",
     "f_sg": "finie",
     "m_pl": "finis",
     "f_pl": "finies"
    }
   },
   {
    "lemma": "vendre",
    "gloss": "sell",
    "kind": "regular -re, third group",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "Le Conjugueur: the general pattern of verbs in -dre, except prendre. The third person singular of the present is vend, with no added letter. The future stem drops the final e of the infinitive: vendr-.",
    "present": {
     "1s": "vends",
     "2s": "vends",
     "3s": "vend",
     "1p": "vendons",
     "2p": "vendez",
     "3p": "vendent"
    },
    "passe_compose": {
     "1s": "ai vendu",
     "2s": "as vendu",
     "3s": "a vendu",
     "1p": "avons vendu",
     "2p": "avez vendu",
     "3p": "ont vendu"
    },
    "imparfait": {
     "1s": "vendais",
     "2s": "vendais",
     "3s": "vendait",
     "1p": "vendions",
     "2p": "vendiez",
     "3p": "vendaient"
    },
    "futur": {
     "1s": "vendrai",
     "2s": "vendras",
     "3s": "vendra",
     "1p": "vendrons",
     "2p": "vendrez",
     "3p": "vendront"
    },
    "subjonctif": {
     "1s": "vende",
     "2s": "vendes",
     "3s": "vende",
     "1p": "vendions",
     "2p": "vendiez",
     "3p": "vendent"
    },
    "participe_present": "vendant",
    "participe_passe": {
     "m_sg": "vendu",
     "f_sg": "vendue",
     "m_pl": "vendus",
     "f_pl": "vendues"
    }
   },
   {
    "lemma": "aller",
    "gloss": "go",
    "kind": "irregular, third group",
    "auxiliary": "être",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "The main table prints the masculine participle. The feminine cells are the participle list on the same page, joined to the same auxiliary. Vous is êtes allé for one man, êtes allée for one woman, êtes allés for a masculine or mixed group, and êtes allées for a feminine group. The stored 2p cell is the plural masculine that the main table prints. It is not asked.",
    "present": {
     "1s": "vais",
     "2s": "vas",
     "3s": "va",
     "1p": "allons",
     "2p": "allez",
     "3p": "vont"
    },
    "passe_compose": {
     "1s": "suis allé",
     "2s": "es allé",
     "3s": "est allé",
     "1p": "sommes allés",
     "2p": "êtes allés",
     "3p": "sont allés",
     "1s_f": "suis allée",
     "2s_f": "es allée",
     "3s_f": "est allée",
     "1p_f": "sommes allées",
     "3p_f": "sont allées"
    },
    "imparfait": {
     "1s": "allais",
     "2s": "allais",
     "3s": "allait",
     "1p": "allions",
     "2p": "alliez",
     "3p": "allaient"
    },
    "futur": {
     "1s": "irai",
     "2s": "iras",
     "3s": "ira",
     "1p": "irons",
     "2p": "irez",
     "3p": "iront"
    },
    "subjonctif": {
     "1s": "aille",
     "2s": "ailles",
     "3s": "aille",
     "1p": "allions",
     "2p": "alliez",
     "3p": "aillent"
    },
    "participe_present": "allant",
    "participe_passe": {
     "m_sg": "allé",
     "f_sg": "allée",
     "m_pl": "allés",
     "f_pl": "allées"
    }
   },
   {
    "lemma": "faire",
    "gloss": "do, make",
    "kind": "irregular, third group",
    "auxiliary": "avoir",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "Le Conjugueur notes the second person plural faites beside nous faisons. The future stem is fer-. The participle agrees when it is a preceding direct object: faite, faits, faites. Those cells are stored and are not asked.",
    "present": {
     "1s": "fais",
     "2s": "fais",
     "3s": "fait",
     "1p": "faisons",
     "2p": "faites",
     "3p": "font"
    },
    "passe_compose": {
     "1s": "ai fait",
     "2s": "as fait",
     "3s": "a fait",
     "1p": "avons fait",
     "2p": "avez fait",
     "3p": "ont fait"
    },
    "imparfait": {
     "1s": "faisais",
     "2s": "faisais",
     "3s": "faisait",
     "1p": "faisions",
     "2p": "faisiez",
     "3p": "faisaient"
    },
    "futur": {
     "1s": "ferai",
     "2s": "feras",
     "3s": "fera",
     "1p": "ferons",
     "2p": "ferez",
     "3p": "feront"
    },
    "subjonctif": {
     "1s": "fasse",
     "2s": "fasses",
     "3s": "fasse",
     "1p": "fassions",
     "2p": "fassiez",
     "3p": "fassent"
    },
    "participe_present": "faisant",
    "participe_passe": {
     "m_sg": "fait",
     "f_sg": "faite",
     "m_pl": "faits",
     "f_pl": "faites"
    }
   },
   {
    "lemma": "venir",
    "gloss": "come",
    "kind": "irregular, third group",
    "auxiliary": "être",
    "ref": "Le Conjugueur, lefigaro.fr, read 2026-10-09",
    "note": "The auxiliary is être, as for aller. The main table prints the masculine participle. Feminine cells are on the same page’s participle list. The future stem is viendr-. Vous follows the same split as aller, and the stored 2p cell is the table’s masculine plural. It is not asked. Venir de plus an infinitive means to have just done, and that construction is not asked.",
    "present": {
     "1s": "viens",
     "2s": "viens",
     "3s": "vient",
     "1p": "venons",
     "2p": "venez",
     "3p": "viennent"
    },
    "passe_compose": {
     "1s": "suis venu",
     "2s": "es venu",
     "3s": "est venu",
     "1p": "sommes venus",
     "2p": "êtes venus",
     "3p": "sont venus",
     "1s_f": "suis venue",
     "2s_f": "es venue",
     "3s_f": "est venue",
     "1p_f": "sommes venues",
     "3p_f": "sont venues"
    },
    "imparfait": {
     "1s": "venais",
     "2s": "venais",
     "3s": "venait",
     "1p": "venions",
     "2p": "veniez",
     "3p": "venaient"
    },
    "futur": {
     "1s": "viendrai",
     "2s": "viendras",
     "3s": "viendra",
     "1p": "viendrons",
     "2p": "viendrez",
     "3p": "viendront"
    },
    "subjonctif": {
     "1s": "vienne",
     "2s": "viennes",
     "3s": "vienne",
     "1p": "venions",
     "2p": "veniez",
     "3p": "viennent"
    },
    "participe_present": "venant",
    "participe_passe": {
     "m_sg": "venu",
     "f_sg": "venue",
     "m_pl": "venus",
     "f_pl": "venues"
    }
   }
  ]
 },
 "cards": {
  "title": "French beside Latin",
  "description": "What modern French has, and where it differs from Latin.",
  "cards": [
   {
    "heading": "Modern French",
    "text": "We set modern French beside Latin. The forms here are the forms of standard written French, the French of the school grammar and of the dictionary. We do not use Old French, and we do not use a regional dialect."
   },
   {
    "heading": "Accents and the cedilla",
    "text": "French writes an accent on a vowel, and it writes a cedilla under c. The acute, as in été, the grave, as in où and à, and the circumflex, as in être, belong to the spelling. The cedilla, as in français, marks that c is pronounced s before a, o, or u. An accent can distinguish two words, so a and à are not the same word, and ou and où are not the same word. Latin, as we print it, uses the macron for quantity. French uses these marks as letters of the word."
   },
   {
    "heading": "The article",
    "text": "French has an article, and Latin has none. The article stands with its noun and agrees with the noun in gender and number. Le roi means the king, and un roi means a king. A French noun in an ordinary sentence has an article or some other determiner. We count the article as a part of speech in French, as the Greek grammarians counted it in Greek."
   },
   {
    "heading": "The forms of the article",
    "text": "The definite article is le before a masculine singular noun, la before a feminine singular noun, and les before a plural noun. Before a vowel or a mute h, an h that is not pronounced, le and la become l’. The indefinite article is un, une, and des. The partitive, for an unspecified amount, is du, de la, de l’, and des. À contracts with le and les, and the results are au and aux. De contracts with le and les, and the results are du and des. À la, à l’, de la, and de l’ stay in two words."
   },
   {
    "heading": "Gender",
    "text": "Every French noun is masculine or feminine. Latin has a third gender, the neuter, and French has none. The article shows the gender. Le livre is masculine, and la table is feminine. The ending does not always show the gender, since livre ends in e and is masculine, and victoire is feminine for a reason the ending alone does not settle."
   },
   {
    "heading": "Number",
    "text": "A French noun has two numbers, the singular and the plural, as a Latin noun has. A regular plural adds s, and that s is usually silent. Some plurals change the stem. The plural of cheval is chevaux, and the plural of cadeau is cadeaux. The article marks number as well. Les is plural, and le and la are singular."
   },
   {
    "heading": "No case on the noun",
    "text": "A French noun does not change for case. Latin marks the nominative, the genitive, the dative, the accusative, the ablative, and the vocative on the noun. French keeps one form of the noun for the subject, for the object, and for the object of a preposition. In le roi vend le cheval, each noun has the form it would have in another place in the sentence. What Latin marks by case, French marks by the order of the words and by the preposition, and, for a pronoun, by a change of form."
   },
   {
    "heading": "Adjective agreement",
    "text": "An adjective agrees with its noun in gender and number. It does not agree in case, because the noun has no case. Un bon roi is masculine and singular, une bonne femme is feminine and singular, les bons rois is masculine and plural, and les bonnes femmes is feminine and plural. Bon adds e for the feminine and s for the plural, and the feminine singular doubles the n, so the form is bonne. A short adjective such as bon, petit, or grand usually stands before the noun."
   },
   {
    "heading": "Subject, object, and stressed pronouns",
    "text": "The pronoun keeps a difference that the noun has lost. The subject forms are je, tu, il, elle, on, nous, vous, ils, and elles. The direct-object forms are me, te, le, la, nous, vous, and les. The indirect-object forms are me, te, lui, nous, vous, and leur. The stressed forms, also called disjunctive, are moi, toi, lui, elle, soi, nous, vous, eux, and elles. Je is the subject of the verb, me is the object, and moi stands where the form is stressed, above all after a preposition. Nous and vous have one spelling in all four uses, so the place in the sentence shows the use."
   },
   {
    "heading": "Person and number",
    "text": "The ending of the verb, together with the subject pronoun, shows the person and the number. Latin often leaves the subject pronoun out, because the ending is enough. French writes the pronoun in an ordinary statement. The subject of je parle is the speaker. The subject of il parle is he, or a masculine it. The subject of ils parlent is they. Elles is used for a group that is feminine throughout, and ils is used for a masculine group and for a mixed group. On takes the third person singular, whether it means one, or people, or we."
   },
   {
    "heading": "The present",
    "text": "The present indicative says that the action goes on now, or that it is habitual, or that it is so in general. Il parle means he speaks, or he is speaking. A regular verb in -er, such as parler, has the endings e, es, e, ons, ez, and ent. A regular verb in -ir of the finir type inserts -iss- in the plural: finis, finis, finit, finissons, finissez, finissent. A regular verb in -re of the vendre type has vends, vends, vend, vendons, vendez, vendent. The third person singular of vendre adds no letter."
   },
   {
    "heading": "The passé composé",
    "text": "The passé composé is the ordinary past of a completed action. Latin uses the perfect for that past. Il a parlé means he spoke, or he has spoken. The form is the present of avoir or of être, with the past participle. Parler, finir, vendre, faire, être, and avoir take avoir. Aller and venir take être, and the participle then agrees with the subject, so elle est allée and ils sont venus. With avoir, the participle does not agree with the subject. It agrees with a direct object that stands before the verb. That further agreement is real, and a single cell of the table does not show the sentence in which it is made."
   },
   {
    "heading": "The imparfait",
    "text": "The imparfait says that the action went on in the past, or that it was habitual then. Il parlait means he was speaking, or he used to speak. The passé composé does not by itself say either of those things. The endings are ais, ais, ait, ions, iez, aient, on the stem of the first person plural of the present, without -ons. Nous parlions is the spelling of the imparfait of parler, and it is also the spelling of the present subjunctive. The rest of the sentence shows which is meant."
   },
   {
    "heading": "The future",
    "text": "The future says that the action will happen. Il parlera means he will speak. A regular verb takes the infinitive as its stem, or the infinitive of an -re verb without the final e, and then the endings ai, as, a, ons, ez, ont. Être, avoir, aller, faire, and venir do not use that stem. Their future stems are ser-, aur-, ir-, fer-, and viendr-. Je serai is the future of être. Je serais is the conditional, which is another mood, and it is not the future."
   },
   {
    "heading": "Être and avoir",
    "text": "Être means be, as Latin sum does, and avoir means have. Both are irregular, and both are auxiliaries of the passé composé. Avoir forms that tense for most verbs, as in j’ai parlé. Être forms it for aller and for venir, and for the other verbs of motion and of change of state that go with them, as in je suis allé and je suis venu. Être itself takes avoir, so the passé composé is j’ai été. The participle été does not take a feminine ending."
   },
   {
    "heading": "The three groups",
    "text": "The school grammar sorts the verbs into three groups. The first group is the verbs in -er, except aller, and parler is the model. The second group is the verbs in -ir that take -iss-, and finir is the model. The third group holds the rest, including the verbs in -re, such as vendre, and the irregulars, such as aller, faire, and venir. Aller ends in -er and still belongs to the third group. From the model we build the other regular verbs of that group. A third-group verb has to be learned from its own table."
   },
   {
    "heading": "Stem and ending",
    "text": "The form in the sentence is a stem and an ending. In parlons the ending -ons marks the first person plural, and in finissons the same ending follows -iss-. In parlé the ending marks the past participle of an -er verb. The subject pronoun marks the person a second time, because several written endings of an -er verb are pronounced alike. The ending and the pronoun together mark the person and the number."
   },
   {
    "heading": "Elision",
    "text": "A small set of words drops a final vowel before another vowel or a mute h, and the spelling marks the loss with an apostrophe. Je, me, te, le, la, ne, de, and que do this, so the written forms are j’ai, l’ami, and d’un roi. Si drops its vowel only before il and ils. The elided spelling is the same word, not a new one. L’ami is le or la with the vowel dropped, and the gender is still the gender of the noun."
   }
  ]
 },
 "shared": {
  "pos": [
   {
    "id": "fpos1",
    "s": "<b>Le</b> roi parle.",
    "orig": "The king speaks.",
    "a": "article",
    "note": "Le points out the king. French has a definite article, and Latin has none.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos2",
    "s": "La femme finit <b>le</b> livre.",
    "orig": "The woman finishes the book.",
    "a": "article",
    "note": "Le points out the book. The article agrees with livre, which is masculine and singular.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos3",
    "s": "Le <b>roi</b> parle.",
    "orig": "The king speaks.",
    "a": "noun",
    "note": "Roi names the king, and it is the subject of parle.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos4",
    "s": "Le roi vend le <b>cheval</b>.",
    "orig": "The king sells the horse.",
    "a": "noun",
    "note": "Cheval names the horse, and it is the object of vend.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos5",
    "s": "Le roi <b>parle</b>.",
    "orig": "The king speaks.",
    "a": "verb",
    "note": "Parle says what the king does. It is the present, third person singular, of parler.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fpos6",
    "s": "La femme <b>finit</b> le livre.",
    "orig": "The woman finishes the book.",
    "a": "verb",
    "note": "Finit says what the woman does. It is the present, third person singular, of finir.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fpos7",
    "s": "Le <b>bon</b> roi parle.",
    "orig": "The good king speaks.",
    "a": "adjective",
    "note": "Bon tells what sort of king, and it agrees with roi.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos8",
    "s": "La <b>belle</b> femme parle.",
    "orig": "The beautiful woman speaks.",
    "a": "adjective",
    "note": "Belle tells what sort of woman, and it agrees with femme.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos9",
    "s": "Le roi parle <b>bien</b>.",
    "orig": "The king speaks well.",
    "a": "adverb",
    "note": "Bien tells how he speaks. The adverb keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos10",
    "s": "Il vient <b>souvent</b>.",
    "orig": "He comes often.",
    "a": "adverb",
    "note": "Souvent tells how often he comes. The adverb keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos11",
    "s": "Il va <b>dans</b> la ville.",
    "orig": "He goes into the city.",
    "a": "preposition",
    "note": "Dans stands before the noun and marks the place. The noun itself does not change.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos12",
    "s": "Elle parle <b>avec</b> le roi.",
    "orig": "She speaks with the king.",
    "a": "preposition",
    "note": "Avec stands before the noun and marks the company. The noun itself does not change.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos13",
    "s": "Le roi <b>et</b> la femme parlent.",
    "orig": "The king and the woman speak.",
    "a": "conjunction",
    "note": "Et joins the two nouns. The verb is plural because the subject is the two of them.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos14",
    "s": "Le roi parle, <b>mais</b> la femme finit.",
    "orig": "The king speaks, but the woman finishes.",
    "a": "conjunction",
    "note": "Mais joins the two statements and marks the contrast.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos15",
    "s": "<b>Il</b> parle.",
    "orig": "He speaks.",
    "a": "pronoun",
    "note": "Il stands for a masculine subject. Latin would often leave the pronoun out.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos16",
    "s": "Le roi <b>le</b> vend.",
    "orig": "The king sells it.",
    "a": "pronoun",
    "note": "Le stands for the thing sold, and no noun follows it, so it is a pronoun and not the article.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos17",
    "s": "Le roi a <b>parlé</b>.",
    "orig": "The king has spoken.",
    "a": "participle",
    "note": "Parlé is the past participle of parler. With a it makes the passé composé.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fpos18",
    "s": "La femme, <b>parlant</b> au roi, finit le livre.",
    "orig": "The woman, speaking to the king, finishes the book.",
    "a": "participle",
    "note": "Parlant is the present participle of parler. It stands beside the finite verb finit.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fpos19",
    "s": "<b>Hélas</b>, le roi vient.",
    "orig": "Alas, the king is coming.",
    "a": "interjection",
    "note": "Hélas is a cry, and it keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fpos20",
    "s": "<b>Ah</b>, la femme vient.",
    "orig": "Ah, the woman is coming.",
    "a": "interjection",
    "note": "Ah is a cry, and it keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   }
  ],
  "decline": [
   {
    "id": "fdec1",
    "s": "Le <b>roi</b> parle.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a noun, which takes endings",
    "ds": [
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Roi is a noun. It takes an ending for number, and the plural is rois. It takes no ending for case.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec2",
    "s": "Le roi vend le <b>cheval</b>.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a noun, which takes endings",
    "ds": [
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Cheval is a noun. The plural is chevaux, so the word takes an ending for number.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec3",
    "s": "Le roi <b>parle</b>.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a verb, which takes endings",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Parle is a verb. It takes endings for person, number, and tense.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec4",
    "s": "La femme <b>finit</b> le livre.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a verb, which takes endings",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Finit is a verb. It takes endings for person, number, and tense.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec7",
    "s": "<b>Je</b> parle.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a pronoun, which still shows case",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Je is a pronoun. The object form is me, and the stressed form is moi, so the pronoun still changes its form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec8",
    "s": "Le roi <b>le</b> vend.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Declinable: a pronoun, which still shows case",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Le here is a pronoun, the direct object. The subject form for a masculine thing is il, so the pronoun still changes its form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec9",
    "s": "Le roi parle <b>bien</b>.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: an adverb, which keeps one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Bien is an adverb. It keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec10",
    "s": "Il vient <b>souvent</b>.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: an adverb, which keeps one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Souvent is an adverb. It keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec11",
    "s": "Il va <b>dans</b> la ville.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: a preposition, one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Dans is a preposition. It keeps one form, and the noun after it does not give it an ending.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec12",
    "s": "Elle parle <b>avec</b> le roi.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: a preposition, one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a conjunction, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Avec is a preposition. It keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec13",
    "s": "Le roi <b>et</b> la femme parlent.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: a conjunction, one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Et is a conjunction. It keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec14",
    "s": "Le roi parle, <b>mais</b> la femme finit.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: a conjunction, one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: an interjection, one form"
    ],
    "why": "Mais is a conjunction. It keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fdec15",
    "s": "<b>Hélas</b>, le roi vient.",
    "q": "Is the marked word declinable or indeclinable?",
    "a": "Indeclinable: an interjection, one form",
    "ds": [
     "Declinable: a noun, which takes endings",
     "Declinable: a verb, which takes endings",
     "Declinable: an adjective, which takes degrees",
     "Declinable: a pronoun, which still shows case",
     "Indeclinable: an adverb, which keeps one form",
     "Indeclinable: a preposition, one form",
     "Indeclinable: a conjunction, one form"
    ],
    "why": "Hélas is an interjection, a cry, and it keeps one form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   }
  ],
  "cases": [
   {
    "id": "fcase1",
    "s": "<b>Je</b> parle au roi.",
    "q": "What form is the marked pronoun?",
    "a": "Subject form",
    "ds": [
     "Direct-object form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "Je is the subject of parle, so the pronoun is in the subject form. The object form is me, and the stressed form is moi.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase2",
    "s": "<b>Elle</b> finit le livre.",
    "q": "What form is the marked pronoun?",
    "a": "Subject form",
    "ds": [
     "Direct-object form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "Elle is the subject of finit, so the pronoun is in the subject form. After a preposition the same letters are the stressed form, and there is no preposition here.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase3",
    "s": "Le roi <b>le</b> vend.",
    "q": "What form is the marked pronoun?",
    "a": "Direct-object form",
    "ds": [
     "Subject form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "Le is the thing sold, and it is the direct object of vend. The pronoun stands before the verb.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase4",
    "s": "La femme <b>les</b> finit.",
    "q": "What form is the marked pronoun?",
    "a": "Direct-object form",
    "ds": [
     "Subject form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "Les is the thing finished, and it is plural. It is the direct object of finit, and it stands before the verb.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase5",
    "s": "Il <b>l’</b>a.",
    "q": "What form is the marked pronoun?",
    "a": "Direct-object form",
    "ds": [
     "Subject form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "L’ is le or la before the vowel of a. It is the direct object of a, from avoir, and it stands before the verb.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase6",
    "s": "Le roi <b>lui</b> parle.",
    "q": "What form is the marked pronoun?",
    "a": "Indirect-object form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Stressed form"
    ],
    "why": "Parler takes à for the person spoken to. When that person is a pronoun before the verb, the form is lui, the indirect object. Lui here is not the stressed pronoun, because no preposition is written.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase7",
    "s": "La femme <b>leur</b> parle.",
    "q": "What form is the marked pronoun?",
    "a": "Indirect-object form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Stressed form"
    ],
    "why": "Leur is the indirect object, plural, of parle. The person spoken to would be marked by à if the noun were written out.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase8",
    "s": "Elle parle avec <b>moi</b>.",
    "q": "What form is the marked pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "Avec is a preposition, and the pronoun after it is the stressed form. Moi is that form. Je cannot stand there.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase9",
    "s": "Le roi vient avec <b>eux</b>.",
    "q": "What form is the marked pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "Eux is the stressed form, masculine plural, after the preposition avec. The subject form would be ils.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fcase10",
    "s": "C’est <b>toi</b>.",
    "q": "What form is the marked pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "After c’est the pronoun is the stressed form. Toi is that form, and tu is the subject form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   }
  ],
  "govern": [
   {
    "id": "fgov1",
    "s": "Elle parle avec <b>moi</b>.",
    "q": "What form does avec require of the pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "Avec is a preposition, so the pronoun is the stressed form. Moi is that form. Je is the subject form, and it does not stand after avec.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov2",
    "s": "Le livre est pour <b>toi</b>.",
    "q": "What form does pour require of the pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "Pour is a preposition, so the pronoun is the stressed form. Toi is that form, and tu is the subject form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov3",
    "s": "Il vient sans <b>elle</b>.",
    "q": "What form does sans require of the pronoun?",
    "a": "Stressed form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Indirect-object form"
    ],
    "why": "Sans is a preposition, so the pronoun is the stressed form. Elle is spelled like the subject form, and the use after the preposition is still the stressed one. Il would not stand there.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov4",
    "s": "Le roi <b>lui</b> parle.",
    "q": "What form does parler à take when the pronoun stands before the verb?",
    "a": "Indirect-object form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Stressed form after a preposition"
    ],
    "why": "Parler à marks the person spoken to. Before the verb that person is lui, the indirect object. The stressed form would follow a written preposition, and this sentence has none.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov5",
    "s": "La femme <b>leur</b> vend le livre.",
    "q": "What form does vendre à take for the buyer, when the pronoun stands before the verb?",
    "a": "Indirect-object form",
    "ds": [
     "Subject form",
     "Direct-object form",
     "Stressed form after a preposition"
    ],
    "why": "Vendre à marks the buyer. Before the verb the buyer is leur, the indirect object. Le livre is the thing sold, and it stays a noun here.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov6",
    "s": "La femme <b>le</b> finit.",
    "q": "What form does finir take for the thing finished?",
    "a": "Direct-object form",
    "ds": [
     "Subject form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "The thing finished is the direct object. Le stands for it and stands before finit. Lui would be a person spoken to, which finir does not take in this sentence.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov7",
    "s": "Il <b>l’</b>a.",
    "q": "What form does avoir take for the thing had?",
    "a": "Direct-object form",
    "ds": [
     "Subject form",
     "Indirect-object form",
     "Stressed form"
    ],
    "why": "The thing had is the direct object of a. L’ is that pronoun before a vowel. Avoir does not put the thing had in a stressed form.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fgov8",
    "s": "Il va dans la <b>ville</b>.",
    "q": "What case does dans give the noun?",
    "a": "No case on the noun",
    "ds": [
     "Dative",
     "The accusative, as Latin uses for motion",
     "The ablative, as Latin uses for place where"
    ],
    "why": "Dans marks the place, and ville does not change its form. French does not put the noun in the accusative for motion or in the ablative for place. Latin in does make that difference.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   }
  ],
  "agree": [
   {
    "id": "fagr1",
    "form": "bon roi",
    "gloss": "bon, good &nbsp;·&nbsp; roi, masculine, king",
    "q": "Judge the phrase.",
    "a": "Sound: the adjective agrees with its noun",
    "ds": [
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Roi is masculine and singular. Bon is the masculine singular, so the adjective agrees. French marks no case on either word.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr2",
    "form": "belle femme",
    "gloss": "beau, beautiful &nbsp;·&nbsp; femme, feminine, woman",
    "q": "Judge the phrase.",
    "a": "Sound: the adjective agrees with its noun",
    "ds": [
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Femme is feminine and singular. Belle is the feminine singular of beau, so the adjective agrees.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr3",
    "form": "beaux chevaux",
    "gloss": "beau, beautiful &nbsp;·&nbsp; cheval, masculine, horse",
    "q": "Judge the phrase.",
    "a": "Sound: the adjective agrees with its noun",
    "ds": [
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Chevaux is masculine and plural. Beaux is the masculine plural of beau, so the adjective agrees.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr4",
    "form": "vieil ami",
    "gloss": "vieux, old &nbsp;·&nbsp; ami, masculine, friend",
    "q": "Judge the phrase.",
    "a": "Sound: the adjective agrees with its noun",
    "ds": [
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Ami is masculine and singular, and it begins with a vowel. Vieil is the masculine singular of vieux used before a vowel, so the adjective agrees. Lawless requires that form.",
    "lang": "fr",
    "src": [
     "lawless",
     "larousse"
    ]
   },
   {
    "id": "fagr5",
    "form": "bon femme",
    "gloss": "bon, good &nbsp;·&nbsp; femme, feminine, woman",
    "q": "Judge the phrase.",
    "a": "Faulty: the adjective disagrees in <b>gender</b>",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Femme is feminine. Bon is masculine, so the adjective disagrees in gender. Both words are singular, and French marks no case here.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr6",
    "form": "belle roi",
    "gloss": "beau, beautiful &nbsp;·&nbsp; roi, masculine, king",
    "q": "Judge the phrase.",
    "a": "Faulty: the adjective disagrees in <b>gender</b>",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Roi is masculine. Belle is feminine, so the adjective disagrees in gender. Number is singular on both words.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr7",
    "form": "heureux femme",
    "gloss": "heureux, happy &nbsp;·&nbsp; femme, feminine, woman",
    "q": "Judge the phrase.",
    "a": "Faulty: the adjective disagrees in <b>gender</b>",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Femme is feminine. Heureux is the masculine form, and the feminine is heureuse, so the adjective disagrees in gender.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr8",
    "form": "petit table",
    "gloss": "petit, small &nbsp;·&nbsp; table, feminine, table",
    "q": "Judge the phrase.",
    "a": "Faulty: the adjective disagrees in <b>gender</b>",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the <b>number</b> does not agree",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Table is feminine. Petit is masculine, and the feminine is petite, so the adjective disagrees in gender.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr9",
    "form": "bon rois",
    "gloss": "bon, good &nbsp;·&nbsp; roi, masculine, king",
    "q": "Judge the phrase.",
    "a": "Faulty: the <b>number</b> does not agree",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Rois is plural. Bon is singular, and the masculine plural is bons, so the number does not agree. Both words are masculine.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fagr10",
    "form": "beaux cheval",
    "gloss": "beau, beautiful &nbsp;·&nbsp; cheval, masculine, horse",
    "q": "Judge the phrase.",
    "a": "Faulty: the <b>number</b> does not agree",
    "ds": [
     "Sound: the adjective agrees with its noun",
     "Faulty: the adjective disagrees in <b>gender</b>",
     "Faulty: the adjective does not agree in <b>case</b>"
    ],
    "why": "Cheval is singular. Beaux is plural, so the number does not agree. Both words are masculine.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   }
  ],
  "produce": [
   {
    "id": "fprod1",
    "lemma": "roi",
    "lemmaLine": "roi, rois, masculine, king",
    "want": "plural",
    "a": "rois",
    "why": "The plural of roi adds s. The singular is roi.",
    "lang": "fr",
    "src": [
     "larousse"
    ]
   },
   {
    "id": "fprod2",
    "lemma": "cheval",
    "lemmaLine": "cheval, chevaux, masculine, horse",
    "want": "plural",
    "a": "chevaux",
    "why": "The plural of cheval is chevaux. The stem changes, and the ending is x.",
    "lang": "fr",
    "src": [
     "larousse"
    ]
   },
   {
    "id": "fprod3",
    "lemma": "cadeau",
    "lemmaLine": "cadeau, cadeaux, masculine, gift",
    "want": "plural",
    "a": "cadeaux",
    "why": "The plural of cadeau is cadeaux. A noun in -eau takes -x.",
    "lang": "fr",
    "src": [
     "larousse"
    ]
   },
   {
    "id": "fprod4",
    "lemma": "ami",
    "lemmaLine": "ami, amie, masculine, friend",
    "want": "feminine singular",
    "a": "amie",
    "why": "The feminine of ami is amie. The article before it is l’, because the word begins with a vowel.",
    "lang": "fr",
    "src": [
     "larousse"
    ]
   },
   {
    "id": "fprod5",
    "lemma": "bon",
    "lemmaLine": "bon, bonne, good",
    "want": "feminine singular",
    "a": "bonne",
    "why": "The feminine singular of bon is bonne. The n is doubled.",
    "lang": "fr",
    "src": [
     "lawless"
    ]
   },
   {
    "id": "fprod6",
    "lemma": "beau",
    "lemmaLine": "beau, bel, belle, beautiful",
    "want": "masculine singular used before a vowel",
    "a": "bel",
    "why": "Before a masculine noun that begins with a vowel, beau becomes bel. Larousse gives bel as that form.",
    "lang": "fr",
    "src": [
     "lawless",
     "larousse"
    ]
   },
   {
    "id": "fprod7",
    "lemma": "vieux",
    "lemmaLine": "vieux, vieil, vieille, old",
    "want": "feminine plural",
    "a": "vieilles",
    "why": "The feminine plural of vieux is vieilles.",
    "lang": "fr",
    "src": [
     "lawless",
     "larousse"
    ]
   },
   {
    "id": "fprod8",
    "lemma": "heureux",
    "lemmaLine": "heureux, heureuse, happy",
    "want": "feminine singular",
    "a": "heureuse",
    "why": "The feminine singular of heureux is heureuse. The masculine plural stays heureux.",
    "lang": "fr",
    "src": [
     "larousse"
    ]
   },
   {
    "id": "fprod9",
    "lemma": "parler",
    "lemmaLine": "parler, first group, speak",
    "want": "present indicative, first person plural",
    "a": "parlons",
    "why": "Parlons is the present, first person plural, of parler. The subject pronoun is nous.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod10",
    "lemma": "parler",
    "lemmaLine": "parler, first group, speak",
    "want": "imparfait, third person singular",
    "a": "parlait",
    "why": "Parlait is the imparfait, third person singular. The present subjunctive is parle, so the two are not the same spelling.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod11",
    "lemma": "parler",
    "lemmaLine": "parler, first group, speak",
    "want": "future, third person plural",
    "a": "parleront",
    "why": "Parleront is the future, third person plural. The stem is the infinitive, and the ending is -ont.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod12",
    "lemma": "parler",
    "lemmaLine": "parler, first group, speak",
    "want": "passé composé, third person singular",
    "a": "a parlé",
    "why": "Parler takes avoir. The third person singular is a parlé. The participle does not agree with the subject. The written subject is il or elle, and je would be written j’.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod13",
    "lemma": "finir",
    "lemmaLine": "finir, second group, finish",
    "want": "imparfait, third person singular",
    "a": "finissait",
    "why": "Finissait is the imparfait, third person singular. The present is finit, and the present subjunctive is finisse, so this spelling belongs to the imparfait.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod14",
    "lemma": "finir",
    "lemmaLine": "finir, second group, finish",
    "want": "present subjunctive, third person singular",
    "a": "finisse",
    "why": "Finisse is the present subjunctive, third person singular. The present indicative is finit, so the mood is visible in the spelling.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod15",
    "lemma": "vendre",
    "lemmaLine": "vendre, third group, sell",
    "want": "present indicative, third person singular",
    "a": "vend",
    "why": "Vend is the present, third person singular. No letter is added to the stem.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod16",
    "lemma": "être",
    "lemmaLine": "être, be",
    "want": "present indicative, first person plural",
    "a": "sommes",
    "why": "Sommes is the present, first person plural, of être. The subject pronoun is nous.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod17",
    "lemma": "être",
    "lemmaLine": "être, be",
    "want": "present subjunctive, third person plural",
    "a": "soient",
    "why": "Soient is the present subjunctive, third person plural. The indicative is sont.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod19",
    "lemma": "aller",
    "lemmaLine": "aller, third group, go",
    "want": "present indicative, first person singular",
    "a": "vais",
    "why": "Vais is the present, first person singular, of aller. The stem is va-, and the infinitive stem all- is not used here.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod20",
    "lemma": "aller",
    "lemmaLine": "aller, third group, go",
    "want": "passé composé, third person singular feminine",
    "a": "est allée",
    "why": "Aller takes être, so the participle agrees with a feminine singular subject. The form is est allée. The masculine in the same person is est allé.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod21",
    "lemma": "faire",
    "lemmaLine": "faire, third group, do, make",
    "want": "present indicative, second person plural",
    "a": "faites",
    "why": "Faites is the present, second person plural, of faire. The form is not faisez. The subject pronoun vous takes this ending whether vous means one person or more than one. The feminine plural of the participle is spelled the same way, and this item asks the present.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fprod22",
    "lemma": "venir",
    "lemmaLine": "venir, third group, come",
    "want": "passé composé, third person plural feminine",
    "a": "sont venues",
    "why": "Venir takes être, so the participle agrees. The feminine plural is sont venues. The masculine or mixed plural is sont venus.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   }
  ],
  "cong": [
   {
    "id": "fcong1",
    "s": "Le roi parle.",
    "q": "How does this construction stand?",
    "a": "Complete: the parts fit, and the sentence is finished",
    "ds": [
     "Congruous: the parts fit, but the sense is unfinished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "The article fits the noun, and the noun and the verb fit. A finite verb makes the sentence complete.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong2",
    "s": "La femme a fini le livre.",
    "q": "How does this construction stand?",
    "a": "Complete: the parts fit, and the sentence is finished",
    "ds": [
     "Congruous: the parts fit, but the sense is unfinished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "The parts fit, and the passé composé is a finite verb, so the sentence is complete. Whether she has in fact finished is not asked.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong3",
    "s": "Les chevaux sont venus.",
    "q": "How does this construction stand?",
    "a": "Complete: the parts fit, and the sentence is finished",
    "ds": [
     "Congruous: the parts fit, but the sense is unfinished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "Les agrees with chevaux, and sont venus agrees with that plural masculine subject. The sentence is complete.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong4",
    "s": "Nous avons vendu le cheval.",
    "q": "How does this construction stand?",
    "a": "Complete: the parts fit, and the sentence is finished",
    "ds": [
     "Congruous: the parts fit, but the sense is unfinished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "The pronoun, the verb, and the object fit, and a finite verb finishes the sentence.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong5",
    "s": "Le bon roi",
    "q": "How does this construction stand?",
    "a": "Congruous: the parts fit, but the sense is unfinished",
    "ds": [
     "Complete: the parts fit, and the sentence is finished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "Bon fits roi, and le fits roi. There is no verb, so the sense is not yet complete.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong6",
    "s": "La belle ville",
    "q": "How does this construction stand?",
    "a": "Congruous: the parts fit, but the sense is unfinished",
    "ds": [
     "Complete: the parts fit, and the sentence is finished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "Belle fits ville. There is no verb, so the sense is not yet complete.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong7",
    "s": "Une femme heureuse",
    "q": "How does this construction stand?",
    "a": "Congruous: the parts fit, but the sense is unfinished",
    "ds": [
     "Complete: the parts fit, and the sentence is finished",
     "Incongruous: the parts do not fit with one another, so the construction fails"
    ],
    "why": "Heureuse fits femme. There is no verb, so the sense is not yet complete.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong8",
    "s": "Le roi parlent.",
    "q": "How does this construction stand?",
    "a": "Incongruous: the parts do not fit with one another, so the construction fails",
    "ds": [
     "Complete: the parts fit, and the sentence is finished",
     "Congruous: the parts fit, but the sense is unfinished"
    ],
    "why": "Roi is singular and parlent is plural. The parts do not fit. Parlent is a real form, and the fault is the join.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   },
   {
    "id": "fcong9",
    "s": "Le femme parle.",
    "q": "How does this construction stand?",
    "a": "Incongruous: the parts do not fit with one another, so the construction fails",
    "ds": [
     "Complete: the parts fit, and the sentence is finished",
     "Congruous: the parts fit, but the sense is unfinished"
    ],
    "why": "Femme is feminine and le is masculine. The parts do not fit. Each word is a French form, and the fault is the join.",
    "lang": "fr",
    "src": [
     "lawless",
     "leconjugueur"
    ]
   }
  ],
  "vices": [
   {
    "id": "fvice1",
    "s": "Le roi <b>parlont</b>.",
    "q": "What kind of fault?",
    "a": "Barbarism: a form French does not have",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Parlont is not a form of parler. The third person plural of the present is parlent. The fault is in the one word.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice2",
    "s": "Les <b>chevals</b> viennent.",
    "q": "What kind of fault?",
    "a": "Barbarism: a form French does not have",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Chevals is not the plural of cheval. The plural is chevaux. Viennent is a real form, and the fault is in the one noun.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice3",
    "s": "Nous <b>finisons</b> le livre.",
    "q": "What kind of fault?",
    "a": "Barbarism: a form French does not have",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Finisons is not a form of finir. The first person plural of the present is finissons. The fault is in the one word.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice4",
    "s": "<b>Les</b> femme parlent.",
    "q": "What kind of fault?",
    "a": "Solecism: good forms are badly joined",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Les is a real plural article, and femme is a real singular noun. The two do not agree in number. Parlent fits les, and the fault is the join of les and femme.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice5",
    "s": "Elle parle avec <b>je</b>.",
    "q": "What kind of fault?",
    "a": "Solecism: good forms are badly joined",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Je is a real subject form, and avec is a real preposition. A preposition takes the stressed form, which is moi. The fault is the join.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice6",
    "s": "Le roi <b>parlons</b>.",
    "q": "What kind of fault?",
    "a": "Solecism: good forms are badly joined",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Parlons is a real first person plural. The subject roi is third person singular, so the verb does not fit it.",
    "lang": "fr",
    "src": [
     "leconjugueur"
    ]
   },
   {
    "id": "fvice7",
    "s": "Un <b>beau</b> ami vient.",
    "q": "What kind of fault?",
    "a": "Solecism: good forms are badly joined",
    "ds": [
     "No fault: the sentence is sound",
     "A figure: the poets are allowed this departure"
    ],
    "why": "Beau and ami are both real forms. Before a masculine singular noun that begins with a vowel, the form is bel. Lawless says that special form is required. The fault is the join.",
    "lang": "fr",
    "src": [
     "lawless",
     "larousse"
    ]
   }
  ]
 }
};
