/* Generated by greek/build_greek.js from the JSON files in greek/. Do not edit by hand. */
window.GREEK = {
 "vocab": {
  "language": "grc",
  "dialect": "Attic",
  "source": "Herbert Weir Smyth, Greek Grammar, read at https://grammata.pages.dev/ (college section numbers). Meanings are Smyth's glosses where he gives one.",
  "nouns": [
   {
    "lemma": "χώρᾱ",
    "gen": "χώρᾱς",
    "gender": "f",
    "article": "ἡ",
    "declension": 1,
    "gloss": "land",
    "smyth": 216
   },
   {
    "lemma": "νῑ́κη",
    "gen": "νῑ́κης",
    "gender": "f",
    "article": "ἡ",
    "declension": 1,
    "gloss": "victory",
    "smyth": 216
   },
   {
    "lemma": "θάλαττα",
    "gen": "θαλάττης",
    "gender": "f",
    "article": "ἡ",
    "declension": 1,
    "gloss": "sea",
    "smyth": 216,
    "note": "Smyth's Attic paradigm is θάλαττα, with ττ, not θάλασσα."
   },
   {
    "lemma": "μοῖρα",
    "gen": "μοίρᾱς",
    "gender": "f",
    "article": "ἡ",
    "declension": 1,
    "gloss": "fate",
    "smyth": 216
   },
   {
    "lemma": "νεᾱνίᾱς",
    "gen": "νεᾱνίου",
    "gender": "m",
    "article": "ὁ",
    "declension": 1,
    "gloss": "young man",
    "smyth": 222
   },
   {
    "lemma": "κριτής",
    "gen": "κριτοῦ",
    "gender": "m",
    "article": "ὁ",
    "declension": 1,
    "gloss": "judge",
    "smyth": 222
   },
   {
    "lemma": "ἵππος",
    "gen": "ἵππου",
    "gender": "m",
    "article": "ὁ",
    "declension": 2,
    "gloss": "horse",
    "smyth": 231
   },
   {
    "lemma": "ἄνθρωπος",
    "gen": "ἀνθρώπου",
    "gender": "m",
    "article": "ὁ",
    "declension": 2,
    "gloss": "man",
    "smyth": 231
   },
   {
    "lemma": "ὁδός",
    "gen": "ὁδοῦ",
    "gender": "f",
    "article": "ἡ",
    "declension": 2,
    "gloss": "way",
    "smyth": 231
   },
   {
    "lemma": "δῶρον",
    "gen": "δώρου",
    "gender": "n",
    "article": "τό",
    "declension": 2,
    "gloss": "gift",
    "smyth": 231
   },
   {
    "lemma": "φύλαξ",
    "gen": "φύλακος",
    "gender": "m",
    "article": "ὁ",
    "declension": 3,
    "gloss": "watchman",
    "smyth": 256,
    "note": "§241 also glosses φύλαξ as guard."
   },
   {
    "lemma": "ἐλπίς",
    "gen": "ἐλπίδος",
    "gender": "f",
    "article": "ἡ",
    "declension": 3,
    "gloss": "hope",
    "smyth": 257
   },
   {
    "lemma": "σῶμα",
    "gen": "σώματος",
    "gender": "n",
    "article": "τό",
    "declension": 3,
    "gloss": "body",
    "smyth": 258
   },
   {
    "lemma": "πόλις",
    "gen": "πόλεως",
    "gender": "f",
    "article": "ἡ",
    "declension": 3,
    "gloss": "city",
    "smyth": 268
   },
   {
    "lemma": "βασιλεύς",
    "gen": "βασιλέως",
    "gender": "m",
    "article": "ὁ",
    "declension": 3,
    "gloss": "king",
    "smyth": 275
   }
  ],
  "verbs": [
   {
    "lemma": "λῡ́ω",
    "principal_parts": [
     "λῡ́ω",
     "λῡ́σω",
     "ἔλῡσα",
     "λέλυκα",
     "λέλυμαι",
     "ἐλύθην"
    ],
    "gloss": "loose",
    "smyth": 369,
    "kind": "vowel, uncontracted"
   },
   {
    "lemma": "παιδεύω",
    "principal_parts": [
     "παιδεύω",
     "παιδεύσω",
     "ἐπαίδευσα",
     "πεπαίδευκα",
     "πεπαίδευμαι",
     "ἐπαιδεύθην"
    ],
    "gloss": "educate",
    "smyth": 376,
    "note": "Same uncontracted vowel type as λῡ́ω (§376 a). Smyth prints παιδεύω and παιδεύουσι (§423) and ἐπαίδευον, ἐπαίδευσα, and the pluperfect stem ἐπεπαιδεύκη (§429). The other parts follow that stem, the reduplication of §440, and the recessive accent of §423."
   },
   {
    "lemma": "παύω",
    "principal_parts": [
     "παύω",
     "παύσω",
     "ἔπαυσα",
     "πέπαυκα",
     "πέπαυμαι",
     "ἐπαύθην"
    ],
    "gloss": "stop",
    "smyth": 607,
    "note": "§607 glosses παύω as make cease, and the middle παύομαι as cease. The parts follow λῡ́ω (§369, §440, §423). §489 b notes that a sigma in the aorist of παύω is a later form in the manuscripts, so the aorist passive here is ἐπαύθην."
   },
   {
    "lemma": "φονεύω",
    "principal_parts": [
     "φονεύω",
     "φονεύσω",
     "ἐφόνευσα",
     "πεφόνευκα",
     "πεφόνευμαι",
     "ἐφονεύθην"
    ],
    "gloss": "murder",
    "smyth": 441,
    "note": "§441 prints the perfect πεφόνευκα and the gloss murder. §607 glosses the same verb as slay."
   },
   {
    "lemma": "χορεύω",
    "principal_parts": [
     "χορεύω",
     "χορεύσω",
     "ἐχόρευσα",
     "κεχόρευκα",
     "κεχόρευμαι",
     "ἐχορεύθην"
    ],
    "gloss": "dance",
    "smyth": 441,
    "note": "§441 prints κεχόρευκα. An initial aspirate is reduplicated by the smooth stop (§441)."
   },
   {
    "lemma": "βασιλεύω",
    "principal_parts": [
     "βασιλεύω",
     "βασιλεύσω",
     "ἐβασίλευσα",
     "βεβασίλευκα",
     "βεβασίλευμαι",
     "ἐβασιλεύθην"
    ],
    "gloss": "be king",
    "smyth": 607,
    "note": "§607 glosses βασιλεύω as am king, and names it as a denominative of βασιλεύς. The parts follow παιδεύω."
   },
   {
    "lemma": "βουλεύω",
    "principal_parts": [
     "βουλεύω",
     "βουλεύσω",
     "ἐβούλευσα",
     "βεβούλευκα",
     "βεβούλευμαι",
     "ἐβουλεύθην"
    ],
    "gloss": "consult",
    "smyth": 607,
    "note": "§607 glosses the active βουλεύω as consult, and the middle βουλεύομαι as deliberate. Reduplication of β is βε-, as in βέβλαφα (§440)."
   },
   {
    "lemma": "θεραπεύω",
    "principal_parts": [
     "θεραπεύω",
     "θεραπεύσω",
     "ἐθεράπευσα",
     "τεθεράπευκα",
     "τεθεράπευμαι",
     "ἐθεραπεύθην"
    ],
    "gloss": "tend",
    "smyth": 808,
    "note": "§808 lists θεραπεύω with the gloss tend. Initial θ is reduplicated by τ (§441)."
   },
   {
    "lemma": "πιστεύω",
    "principal_parts": [
     "πιστεύω",
     "πιστεύσω",
     "ἐπίστευσα",
     "πεπίστευκα",
     "πεπίστευμαι",
     "ἐπιστεύθην"
    ],
    "gloss": "trust",
    "smyth": 819,
    "note": "§819 glosses πιστεύω as trust. The parts follow the uncontracted vowel type of παιδεύω (§376 a, §607)."
   },
   {
    "lemma": "θῡ́ω",
    "principal_parts": [
     "θῡ́ω",
     "θῡ́σω",
     "ἔθῡσα",
     "τέθυκα",
     "τέθυμαι",
     "ἐτύθην"
    ],
    "gloss": "sacrifice",
    "smyth": 607,
    "note": "§607 glosses θῡ́ω as sacrifice. §500 gives υ long in the present. §441 prints the perfect τέθυκα, with υ short, as in λέλυκα beside λῡ́ω (§374). §588 prints the aorist passive ἐτύθην."
   },
   {
    "lemma": "κελεύω",
    "principal_parts": [
     "κελεύω",
     "κελεύσω",
     "ἐκέλευσα",
     "κεκέλευκα",
     "κεκέλευσμαι",
     "ἐκελεύσθην"
    ],
    "gloss": "order",
    "smyth": 489,
    "note": "§489 prints κελεύω order, κεκέλευσμαι, ἐκελεύσθην, with σ added. §489 a says that other verbs in -ευω form the aorist passive in -θην, without σ. The perfect active κεκέλευκα was not printed in the sections read."
   },
   {
    "lemma": "γράφω",
    "principal_parts": [
     "γράφω",
     "γράψω",
     "ἔγραψα",
     "γέγραφα",
     "γέγραμμαι",
     "ἐγράφην"
    ],
    "gloss": "write",
    "smyth": 369,
    "note": "The aorist passive in §369 is the second aorist ἐγράφην, not a first aorist."
   },
   {
    "lemma": "πέμπω",
    "principal_parts": [
     "πέμπω",
     "πέμψω",
     "ἔπεμψα",
     "πέπομφα",
     "πέπεμμαι",
     "ἐπέμφθην"
    ],
    "gloss": "send",
    "smyth": 545,
    "note": "§545 prints ἔπεμψα and ἐπεμψάμην, and glosses πέμπω as send. The future πέμψω has the same ψ. §478 and §569 print the second perfect πέπομφα. The perfect middle and the aorist passive were not printed in the sections read."
   },
   {
    "lemma": "εἰμί",
    "principal_parts": [
     "εἰμί",
     "ἔσομαι"
    ],
    "gloss": "am",
    "smyth": 768,
    "note": "εἰμί has only the present and future systems (§768). There is no Attic aorist and no perfect."
   }
  ],
  "adjectives": [
   {
    "lemma": "ἀγαθός",
    "feminine": "ἀγαθή",
    "neuter": "ἀγαθόν",
    "gloss": "good",
    "smyth": 287,
    "class": "first and second, three endings"
   },
   {
    "lemma": "μακρός",
    "feminine": "μακρά",
    "neuter": "μακρόν",
    "gloss": "long",
    "smyth": 287,
    "class": "first and second, three endings, feminine α after ρ"
   },
   {
    "lemma": "ἄξιος",
    "feminine": "ἀξίᾱ",
    "neuter": "ἄξιον",
    "gloss": "worthy",
    "smyth": 287,
    "class": "first and second, three endings, feminine ᾱ after ι"
   },
   {
    "lemma": "σοφός",
    "feminine": "σοφή",
    "neuter": "σοφόν",
    "gloss": "wise",
    "smyth": 287,
    "note": "Listed at §287 with the adjectives declined like ἀγαθός. Oxytone, so the accents sit where they sit in ἀγαθός."
   },
   {
    "lemma": "κακός",
    "feminine": "κακή",
    "neuter": "κακόν",
    "gloss": "bad",
    "smyth": 287,
    "note": "Listed at §287 with the adjectives declined like ἀγαθός."
   },
   {
    "lemma": "ἀληθής",
    "feminine": "ἀληθής",
    "neuter": "ἀληθές",
    "gloss": "true",
    "smyth": 292,
    "class": "third, two endings",
    "stem": "ἀληθεσ-"
   }
  ]
 },
 "paradigms": {
  "language": "grc",
  "dialect": "Attic",
  "source": "Herbert Weir Smyth, Greek Grammar, https://grammata.pages.dev/. Section numbers are the college numbering. Macrons are Smyth's quantity marks. Dual and vocative are included because his tables print them.",
  "article": {
   "lemma": "ὁ, ἡ, τό",
   "smyth": 332,
   "gloss": "the",
   "note": "No vocative. The feminine dual τᾱ́ and ταῖν are very rare and are unknown on Attic prose inscriptions (§332 b); the table prints τώ and τοῖν for all three genders. ὁ, ἡ, οἱ, αἱ are proclitics (§179).",
   "forms": {
    "sg": {
     "nom": {
      "m": "ὁ",
      "f": "ἡ",
      "n": "τό"
     },
     "gen": {
      "m": "τοῦ",
      "f": "τῆς",
      "n": "τοῦ"
     },
     "dat": {
      "m": "τῷ",
      "f": "τῇ",
      "n": "τῷ"
     },
     "acc": {
      "m": "τόν",
      "f": "τήν",
      "n": "τό"
     }
    },
    "du": {
     "nom": {
      "m": "τώ",
      "f": "τώ",
      "n": "τώ"
     },
     "gen": {
      "m": "τοῖν",
      "f": "τοῖν",
      "n": "τοῖν"
     },
     "dat": {
      "m": "τοῖν",
      "f": "τοῖν",
      "n": "τοῖν"
     },
     "acc": {
      "m": "τώ",
      "f": "τώ",
      "n": "τώ"
     }
    },
    "pl": {
     "nom": {
      "m": "οἱ",
      "f": "αἱ",
      "n": "τά"
     },
     "gen": {
      "m": "τῶν",
      "f": "τῶν",
      "n": "τῶν"
     },
     "dat": {
      "m": "τοῖς",
      "f": "ταῖς",
      "n": "τοῖς"
     },
     "acc": {
      "m": "τούς",
      "f": "τᾱ́ς",
      "n": "τά"
     }
    }
   }
  },
  "nouns": [
   {
    "lemma": "χώρᾱ",
    "smyth": 216,
    "forms": {
     "sg": {
      "nom": "χώρᾱ",
      "gen": "χώρᾱς",
      "dat": "χώρᾳ",
      "acc": "χώρᾱν",
      "voc": "χώρᾱ"
     },
     "du": {
      "nom": "χώρᾱ",
      "gen": "χώραιν",
      "dat": "χώραιν",
      "acc": "χώρᾱ",
      "voc": "χώρᾱ"
     },
     "pl": {
      "nom": "χῶραι",
      "gen": "χωρῶν",
      "dat": "χώραις",
      "acc": "χώρᾱς",
      "voc": "χῶραι"
     }
    }
   },
   {
    "lemma": "νῑ́κη",
    "smyth": 216,
    "forms": {
     "sg": {
      "nom": "νῑ́κη",
      "gen": "νῑ́κης",
      "dat": "νῑ́κῃ",
      "acc": "νῑ́κην",
      "voc": "νῑ́κη"
     },
     "du": {
      "nom": "νῑ́κᾱ",
      "gen": "νῑ́καιν",
      "dat": "νῑ́καιν",
      "acc": "νῑ́κᾱ",
      "voc": "νῑ́κᾱ"
     },
     "pl": {
      "nom": "νῖκαι",
      "gen": "νῑκῶν",
      "dat": "νῑ́καις",
      "acc": "νῑ́κᾱς",
      "voc": "νῖκαι"
     }
    }
   },
   {
    "lemma": "θάλαττα",
    "smyth": 216,
    "forms": {
     "sg": {
      "nom": "θάλαττα",
      "gen": "θαλάττης",
      "dat": "θαλάττῃ",
      "acc": "θάλατταν",
      "voc": "θάλαττα"
     },
     "du": {
      "nom": "θαλάττᾱ",
      "gen": "θαλάτταιν",
      "dat": "θαλάτταιν",
      "acc": "θαλάττᾱ",
      "voc": "θαλάττᾱ"
     },
     "pl": {
      "nom": "θάλατται",
      "gen": "θαλαττῶν",
      "dat": "θαλάτταις",
      "acc": "θαλάττᾱς",
      "voc": "θάλατται"
     }
    }
   },
   {
    "lemma": "μοῖρα",
    "smyth": 216,
    "forms": {
     "sg": {
      "nom": "μοῖρα",
      "gen": "μοίρᾱς",
      "dat": "μοίρᾳ",
      "acc": "μοῖραν",
      "voc": "μοῖρα"
     },
     "du": {
      "nom": "μοίρᾱ",
      "gen": "μοίραιν",
      "dat": "μοίραιν",
      "acc": "μοίρᾱ",
      "voc": "μοίρᾱ"
     },
     "pl": {
      "nom": "μοῖραι",
      "gen": "μοιρῶν",
      "dat": "μοίραις",
      "acc": "μοίρᾱς",
      "voc": "μοῖραι"
     }
    }
   },
   {
    "lemma": "νεᾱνίᾱς",
    "smyth": 222,
    "forms": {
     "sg": {
      "nom": "νεᾱνίᾱς",
      "gen": "νεᾱνίου",
      "dat": "νεᾱνίᾳ",
      "acc": "νεᾱνίᾱν",
      "voc": "νεᾱνίᾱ"
     },
     "du": {
      "nom": "νεᾱνίᾱ",
      "gen": "νεᾱνίαιν",
      "dat": "νεᾱνίαιν",
      "acc": "νεᾱνίᾱ",
      "voc": "νεᾱνίᾱ"
     },
     "pl": {
      "nom": "νεᾱνίαι",
      "gen": "νεᾱνιῶν",
      "dat": "νεᾱνίαις",
      "acc": "νεᾱνίᾱς",
      "voc": "νεᾱνίαι"
     }
    },
    "note": "The dative singular is printed on grammata as νεᾱνίᾱι, with iota adscript. The parallel datives in §222 use iota subscript, and the form here is written νεᾱνίᾳ."
   },
   {
    "lemma": "κριτής",
    "smyth": 222,
    "forms": {
     "sg": {
      "nom": "κριτής",
      "gen": "κριτοῦ",
      "dat": "κριτῇ",
      "acc": "κριτήν",
      "voc": "κριτά"
     },
     "du": {
      "nom": "κριτᾱ́",
      "gen": "κριταῖν",
      "dat": "κριταῖν",
      "acc": "κριτᾱ́",
      "voc": "κριτᾱ́"
     },
     "pl": {
      "nom": "κριταί",
      "gen": "κριτῶν",
      "dat": "κριταῖς",
      "acc": "κριτᾱ́ς",
      "voc": "κριταί"
     }
    }
   },
   {
    "lemma": "ἵππος",
    "smyth": 231,
    "forms": {
     "sg": {
      "nom": "ἵππος",
      "gen": "ἵππου",
      "dat": "ἵππῳ",
      "acc": "ἵππον",
      "voc": "ἵππε"
     },
     "du": {
      "nom": "ἵππω",
      "gen": "ἵπποιν",
      "dat": "ἵπποιν",
      "acc": "ἵππω",
      "voc": "ἵππω"
     },
     "pl": {
      "nom": "ἵπποι",
      "gen": "ἵππων",
      "dat": "ἵπποις",
      "acc": "ἵππους",
      "voc": "ἵπποι"
     }
    }
   },
   {
    "lemma": "ἄνθρωπος",
    "smyth": 231,
    "forms": {
     "sg": {
      "nom": "ἄνθρωπος",
      "gen": "ἀνθρώπου",
      "dat": "ἀνθρώπῳ",
      "acc": "ἄνθρωπον",
      "voc": "ἄνθρωπε"
     },
     "du": {
      "nom": "ἀνθρώπω",
      "gen": "ἀνθρώποιν",
      "dat": "ἀνθρώποιν",
      "acc": "ἀνθρώπω",
      "voc": "ἀνθρώπω"
     },
     "pl": {
      "nom": "ἄνθρωποι",
      "gen": "ἀνθρώπων",
      "dat": "ἀνθρώποις",
      "acc": "ἀνθρώπους",
      "voc": "ἄνθρωποι"
     }
    }
   },
   {
    "lemma": "ὁδός",
    "smyth": 231,
    "forms": {
     "sg": {
      "nom": "ὁδός",
      "gen": "ὁδοῦ",
      "dat": "ὁδῷ",
      "acc": "ὁδόν",
      "voc": "ὁδέ"
     },
     "du": {
      "nom": "ὁδώ",
      "gen": "ὁδοῖν",
      "dat": "ὁδοῖν",
      "acc": "ὁδώ",
      "voc": "ὁδώ"
     },
     "pl": {
      "nom": "ὁδοί",
      "gen": "ὁδῶν",
      "dat": "ὁδοῖς",
      "acc": "ὁδούς",
      "voc": "ὁδοί"
     }
    }
   },
   {
    "lemma": "δῶρον",
    "smyth": 231,
    "forms": {
     "sg": {
      "nom": "δῶρον",
      "gen": "δώρου",
      "dat": "δώρῳ",
      "acc": "δῶρον",
      "voc": "δῶρον"
     },
     "du": {
      "nom": "δώρω",
      "gen": "δώροιν",
      "dat": "δώροιν",
      "acc": "δώρω",
      "voc": "δώρω"
     },
     "pl": {
      "nom": "δῶρα",
      "gen": "δώρων",
      "dat": "δώροις",
      "acc": "δῶρα",
      "voc": "δῶρα"
     }
    }
   },
   {
    "lemma": "φύλαξ",
    "smyth": 256,
    "forms": {
     "sg": {
      "nom": "φύλαξ",
      "gen": "φύλακος",
      "dat": "φύλακι",
      "acc": "φύλακα",
      "voc": "φύλαξ"
     },
     "du": {
      "nom": "φύλακε",
      "gen": "φυλάκοιν",
      "dat": "φυλάκοιν",
      "acc": "φύλακε",
      "voc": "φύλακε"
     },
     "pl": {
      "nom": "φύλακες",
      "gen": "φυλάκων",
      "dat": "φύλαξι",
      "acc": "φύλακας",
      "voc": "φύλακες"
     }
    },
    "note": "Dative plural φύλαξι(ν), with movable ν (§256)."
   },
   {
    "lemma": "ἐλπίς",
    "smyth": 257,
    "forms": {
     "sg": {
      "nom": "ἐλπίς",
      "gen": "ἐλπίδος",
      "dat": "ἐλπίδι",
      "acc": "ἐλπίδα",
      "voc": "ἐλπί"
     },
     "du": {
      "nom": "ἐλπίδε",
      "gen": "ἐλπίδοιν",
      "dat": "ἐλπίδοιν",
      "acc": "ἐλπίδε",
      "voc": "ἐλπίδε"
     },
     "pl": {
      "nom": "ἐλπίδες",
      "gen": "ἐλπίδων",
      "dat": "ἐλπίσι",
      "acc": "ἐλπίδας",
      "voc": "ἐλπίδες"
     }
    },
    "note": "Dative plural ἐλπίσι(ν). Vocative singular ἐλπί (§257)."
   },
   {
    "lemma": "σῶμα",
    "smyth": 258,
    "forms": {
     "sg": {
      "nom": "σῶμα",
      "gen": "σώματος",
      "dat": "σώματι",
      "acc": "σῶμα",
      "voc": "σῶμα"
     },
     "du": {
      "nom": "σώματε",
      "gen": "σωμάτοιν",
      "dat": "σωμάτοιν",
      "acc": "σώματε",
      "voc": "σώματε"
     },
     "pl": {
      "nom": "σώματα",
      "gen": "σωμάτων",
      "dat": "σώμασι",
      "acc": "σώματα",
      "voc": "σώματα"
     }
    },
    "note": "Dative plural σώμασι(ν). Nominative, accusative, and vocative are one form in the singular and again in the plural."
   },
   {
    "lemma": "πόλις",
    "smyth": 268,
    "forms": {
     "sg": {
      "nom": "πόλις",
      "gen": "πόλεως",
      "dat": "πόλει",
      "acc": "πόλιν",
      "voc": "πόλι"
     },
     "du": {
      "nom": "πόλει",
      "gen": "πολέοιν",
      "dat": "πολέοιν",
      "acc": "πόλει",
      "voc": "πόλει"
     },
     "pl": {
      "nom": "πόλεις",
      "gen": "πόλεων",
      "dat": "πόλεσι",
      "acc": "πόλεις",
      "voc": "πόλεις"
     }
    },
    "note": "Dative plural πόλεσι(ν). Nominative and accusative plural are both πόλεις (§272). §268 b gives the Homeric forms; they are not entered here."
   },
   {
    "lemma": "βασιλεύς",
    "smyth": 275,
    "forms": {
     "sg": {
      "nom": "βασιλεύς",
      "gen": "βασιλέως",
      "dat": "βασιλεῖ",
      "acc": "βασιλέᾱ",
      "voc": "βασιλεῦ"
     },
     "du": {
      "nom": "βασιλῆ",
      "gen": "βασιλέοιν",
      "dat": "βασιλέοιν",
      "acc": "βασιλῆ",
      "voc": "βασιλῆ"
     },
     "pl": {
      "nom": "βασιλῆς",
      "gen": "βασιλέων",
      "dat": "βασιλεῦσι",
      "acc": "βασιλέᾱς",
      "voc": "βασιλῆς"
     }
    },
    "note": "Nominative and vocative plural: βασιλῆς, and later βασιλεῖς (§275). Dative plural βασιλεῦσι(ν)."
   }
  ],
  "adjectives": [
   {
    "lemma": "ἀγαθός",
    "smyth": 287,
    "forms": {
     "sg": {
      "nom": {
       "m": "ἀγαθός",
       "f": "ἀγαθή",
       "n": "ἀγαθόν"
      },
      "gen": {
       "m": "ἀγαθοῦ",
       "f": "ἀγαθῆς",
       "n": "ἀγαθοῦ"
      },
      "dat": {
       "m": "ἀγαθῷ",
       "f": "ἀγαθῇ",
       "n": "ἀγαθῷ"
      },
      "acc": {
       "m": "ἀγαθόν",
       "f": "ἀγαθήν",
       "n": "ἀγαθόν"
      },
      "voc": {
       "m": "ἀγαθέ",
       "f": "ἀγαθή",
       "n": "ἀγαθόν"
      }
     },
     "du": {
      "nom": {
       "m": "ἀγαθώ",
       "f": "ἀγαθᾱ́",
       "n": "ἀγαθώ"
      },
      "gen": {
       "m": "ἀγαθοῖν",
       "f": "ἀγαθαῖν",
       "n": "ἀγαθοῖν"
      },
      "dat": {
       "m": "ἀγαθοῖν",
       "f": "ἀγαθαῖν",
       "n": "ἀγαθοῖν"
      },
      "acc": {
       "m": "ἀγαθώ",
       "f": "ἀγαθᾱ́",
       "n": "ἀγαθώ"
      },
      "voc": {
       "m": "ἀγαθώ",
       "f": "ἀγαθᾱ́",
       "n": "ἀγαθώ"
      }
     },
     "pl": {
      "nom": {
       "m": "ἀγαθοί",
       "f": "ἀγαθαί",
       "n": "ἀγαθά"
      },
      "gen": {
       "m": "ἀγαθῶν",
       "f": "ἀγαθῶν",
       "n": "ἀγαθῶν"
      },
      "dat": {
       "m": "ἀγαθοῖς",
       "f": "ἀγαθαῖς",
       "n": "ἀγαθοῖς"
      },
      "acc": {
       "m": "ἀγαθούς",
       "f": "ἀγαθᾱ́ς",
       "n": "ἀγαθά"
      },
      "voc": {
       "m": "ἀγαθοί",
       "f": "ἀγαθαί",
       "n": "ἀγαθά"
      }
     }
    },
    "note": "The masculine dual may be used for the feminine dual (§287 b)."
   },
   {
    "lemma": "μακρός",
    "smyth": 287,
    "forms": {
     "sg": {
      "nom": {
       "m": "μακρός",
       "f": "μακρά",
       "n": "μακρόν"
      },
      "gen": {
       "m": "μακροῦ",
       "f": "μακρᾶς",
       "n": "μακροῦ"
      },
      "dat": {
       "m": "μακρῷ",
       "f": "μακρᾷ",
       "n": "μακρῷ"
      },
      "acc": {
       "m": "μακρόν",
       "f": "μακράν",
       "n": "μακρόν"
      },
      "voc": {
       "m": "μακρέ",
       "f": "μακρά",
       "n": "μακρόν"
      }
     },
     "du": {
      "nom": {
       "m": "μακρώ",
       "f": "μακρά",
       "n": "μακρώ"
      },
      "gen": {
       "m": "μακροῖν",
       "f": "μακραῖν",
       "n": "μακροῖν"
      },
      "dat": {
       "m": "μακροῖν",
       "f": "μακραῖν",
       "n": "μακροῖν"
      },
      "acc": {
       "m": "μακρώ",
       "f": "μακρά",
       "n": "μακρώ"
      },
      "voc": {
       "m": "μακρώ",
       "f": "μακρά",
       "n": "μακρώ"
      }
     },
     "pl": {
      "nom": {
       "m": "μακροί",
       "f": "μακραί",
       "n": "μακρά"
      },
      "gen": {
       "m": "μακρῶν",
       "f": "μακρῶν",
       "n": "μακρῶν"
      },
      "dat": {
       "m": "μακροῖς",
       "f": "μακραῖς",
       "n": "μακροῖς"
      },
      "acc": {
       "m": "μακρούς",
       "f": "μακράς",
       "n": "μακρά"
      },
      "voc": {
       "m": "μακροί",
       "f": "μακραί",
       "n": "μακρά"
      }
     }
    }
   },
   {
    "lemma": "ἄξιος",
    "smyth": 287,
    "forms": {
     "sg": {
      "nom": {
       "m": "ἄξιος",
       "f": "ἀξίᾱ",
       "n": "ἄξιον"
      },
      "gen": {
       "m": "ἀξίου",
       "f": "ἀξίᾱς",
       "n": "ἀξίου"
      },
      "dat": {
       "m": "ἀξίῳ",
       "f": "ἀξίᾳ",
       "n": "ἀξίῳ"
      },
      "acc": {
       "m": "ἄξιον",
       "f": "ἀξίᾱν",
       "n": "ἄξιον"
      },
      "voc": {
       "m": "ἄξιε",
       "f": "ἀξίᾱ",
       "n": "ἄξιον"
      }
     },
     "du": {
      "nom": {
       "m": "ἀξίω",
       "f": "ἀξίᾱ",
       "n": "ἀξίω"
      },
      "gen": {
       "m": "ἀξίοιν",
       "f": "ἀξίαιν",
       "n": "ἀξίοιν"
      },
      "dat": {
       "m": "ἀξίοιν",
       "f": "ἀξίαιν",
       "n": "ἀξίοιν"
      },
      "acc": {
       "m": "ἀξίω",
       "f": "ἀξίᾱ",
       "n": "ἀξίω"
      },
      "voc": {
       "m": "ἀξίω",
       "f": "ἀξίᾱ",
       "n": "ἀξίω"
      }
     },
     "pl": {
      "nom": {
       "m": "ἄξιοι",
       "f": "ἄξιαι",
       "n": "ἄξια"
      },
      "gen": {
       "m": "ἀξίων",
       "f": "ἀξίων",
       "n": "ἀξίων"
      },
      "dat": {
       "m": "ἀξίοις",
       "f": "ἀξίαις",
       "n": "ἀξίοις"
      },
      "acc": {
       "m": "ἀξίους",
       "f": "ἀξίᾱς",
       "n": "ἄξια"
      },
      "voc": {
       "m": "ἄξιοι",
       "f": "ἄξιαι",
       "n": "ἄξια"
      }
     }
    },
    "note": "The feminine nominative and genitive plural follow the masculine accent: ἄξιαι, ἀξίων, not ἀξίαι, ἀξιῶν (§287 a)."
   },
   {
    "lemma": "σοφός",
    "smyth": 287,
    "forms": {
     "sg": {
      "nom": {
       "m": "σοφός",
       "f": "σοφή",
       "n": "σοφόν"
      },
      "gen": {
       "m": "σοφοῦ",
       "f": "σοφῆς",
       "n": "σοφοῦ"
      },
      "dat": {
       "m": "σοφῷ",
       "f": "σοφῇ",
       "n": "σοφῷ"
      },
      "acc": {
       "m": "σοφόν",
       "f": "σοφήν",
       "n": "σοφόν"
      },
      "voc": {
       "m": "σοφέ",
       "f": "σοφή",
       "n": "σοφόν"
      }
     },
     "du": {
      "nom": {
       "m": "σοφώ",
       "f": "σοφᾱ́",
       "n": "σοφώ"
      },
      "gen": {
       "m": "σοφοῖν",
       "f": "σοφαῖν",
       "n": "σοφοῖν"
      },
      "dat": {
       "m": "σοφοῖν",
       "f": "σοφαῖν",
       "n": "σοφοῖν"
      },
      "acc": {
       "m": "σοφώ",
       "f": "σοφᾱ́",
       "n": "σοφώ"
      },
      "voc": {
       "m": "σοφώ",
       "f": "σοφᾱ́",
       "n": "σοφώ"
      }
     },
     "pl": {
      "nom": {
       "m": "σοφοί",
       "f": "σοφαί",
       "n": "σοφά"
      },
      "gen": {
       "m": "σοφῶν",
       "f": "σοφῶν",
       "n": "σοφῶν"
      },
      "dat": {
       "m": "σοφοῖς",
       "f": "σοφαῖς",
       "n": "σοφοῖς"
      },
      "acc": {
       "m": "σοφούς",
       "f": "σοφᾱ́ς",
       "n": "σοφά"
      },
      "voc": {
       "m": "σοφοί",
       "f": "σοφαί",
       "n": "σοφά"
      }
     }
    },
    "note": "Declined like ἀγαθός (§287)."
   },
   {
    "lemma": "κακός",
    "smyth": 287,
    "forms": {
     "sg": {
      "nom": {
       "m": "κακός",
       "f": "κακή",
       "n": "κακόν"
      },
      "gen": {
       "m": "κακοῦ",
       "f": "κακῆς",
       "n": "κακοῦ"
      },
      "dat": {
       "m": "κακῷ",
       "f": "κακῇ",
       "n": "κακῷ"
      },
      "acc": {
       "m": "κακόν",
       "f": "κακήν",
       "n": "κακόν"
      },
      "voc": {
       "m": "κακέ",
       "f": "κακή",
       "n": "κακόν"
      }
     },
     "du": {
      "nom": {
       "m": "κακώ",
       "f": "κακᾱ́",
       "n": "κακώ"
      },
      "gen": {
       "m": "κακοῖν",
       "f": "κακαῖν",
       "n": "κακοῖν"
      },
      "dat": {
       "m": "κακοῖν",
       "f": "κακαῖν",
       "n": "κακοῖν"
      },
      "acc": {
       "m": "κακώ",
       "f": "κακᾱ́",
       "n": "κακώ"
      },
      "voc": {
       "m": "κακώ",
       "f": "κακᾱ́",
       "n": "κακώ"
      }
     },
     "pl": {
      "nom": {
       "m": "κακοί",
       "f": "κακαί",
       "n": "κακά"
      },
      "gen": {
       "m": "κακῶν",
       "f": "κακῶν",
       "n": "κακῶν"
      },
      "dat": {
       "m": "κακοῖς",
       "f": "κακαῖς",
       "n": "κακοῖς"
      },
      "acc": {
       "m": "κακούς",
       "f": "κακᾱ́ς",
       "n": "κακά"
      },
      "voc": {
       "m": "κακοί",
       "f": "κακαί",
       "n": "κακά"
      }
     }
    },
    "note": "Declined like ἀγαθός (§287)."
   },
   {
    "lemma": "ἀληθής",
    "smyth": 292,
    "forms": {
     "sg": {
      "nom": {
       "m": "ἀληθής",
       "f": "ἀληθής",
       "n": "ἀληθές"
      },
      "gen": {
       "m": "ἀληθοῦς",
       "f": "ἀληθοῦς",
       "n": "ἀληθοῦς"
      },
      "dat": {
       "m": "ἀληθεῖ",
       "f": "ἀληθεῖ",
       "n": "ἀληθεῖ"
      },
      "acc": {
       "m": "ἀληθῆ",
       "f": "ἀληθῆ",
       "n": "ἀληθές"
      },
      "voc": {
       "m": "ἀληθές",
       "f": "ἀληθές",
       "n": "ἀληθές"
      }
     },
     "du": {
      "nom": {
       "m": "ἀληθεῖ",
       "f": "ἀληθεῖ",
       "n": "ἀληθεῖ"
      },
      "gen": {
       "m": "ἀληθοῖν",
       "f": "ἀληθοῖν",
       "n": "ἀληθοῖν"
      },
      "dat": {
       "m": "ἀληθοῖν",
       "f": "ἀληθοῖν",
       "n": "ἀληθοῖν"
      },
      "acc": {
       "m": "ἀληθεῖ",
       "f": "ἀληθεῖ",
       "n": "ἀληθεῖ"
      },
      "voc": {
       "m": "ἀληθεῖ",
       "f": "ἀληθεῖ",
       "n": "ἀληθεῖ"
      }
     },
     "pl": {
      "nom": {
       "m": "ἀληθεῖς",
       "f": "ἀληθεῖς",
       "n": "ἀληθῆ"
      },
      "gen": {
       "m": "ἀληθῶν",
       "f": "ἀληθῶν",
       "n": "ἀληθῶν"
      },
      "dat": {
       "m": "ἀληθέσι",
       "f": "ἀληθέσι",
       "n": "ἀληθέσι"
      },
      "acc": {
       "m": "ἀληθεῖς",
       "f": "ἀληθεῖς",
       "n": "ἀληθῆ"
      },
      "voc": {
       "m": "ἀληθεῖς",
       "f": "ἀληθεῖς",
       "n": "ἀληθῆ"
      }
     }
    },
    "note": "Masculine and feminine share one set of forms. Dative plural ἀληθέσι(ν). The accusative plural masculine and feminine has the nominative form ἀληθεῖς (§292 b)."
   }
  ],
  "verbs": [
   {
    "lemma": "λῡ́ω",
    "smyth": 383,
    "gloss": "loose",
    "note": "Smyth's printed model of the uncontracted vowel verb is λῡ́ω (§383). παιδεύω belongs to the same class (§376 a). Of παιδεύω, Smyth prints παιδεύω, παιδεύουσι (§423), ἐπαίδευον, and ἐπαίδευσα (§429). The present middle is also the present passive (§356 b). Second person singular middle: λῡ́ῃ or λῡ́ει (§383).",
    "active": {
     "present": {
      "1s": "λῡ́ω",
      "2s": "λῡ́εις",
      "3s": "λῡ́ει",
      "2d": "λῡ́ετον",
      "3d": "λῡ́ετον",
      "1p": "λῡ́ομεν",
      "2p": "λῡ́ετε",
      "3p": "λῡ́ουσι"
     },
     "imperfect": {
      "1s": "ἔλῡον",
      "2s": "ἔλῡες",
      "3s": "ἔλῡε",
      "2d": "ἐλῡ́ετον",
      "3d": "ἐλῡέτην",
      "1p": "ἐλῡ́ομεν",
      "2p": "ἐλῡ́ετε",
      "3p": "ἔλῡον"
     },
     "future": {
      "1s": "λῡ́σω",
      "2s": "λῡ́σεις",
      "3s": "λῡ́σει",
      "2d": "λῡ́σετον",
      "3d": "λῡ́σετον",
      "1p": "λῡ́σομεν",
      "2p": "λῡ́σετε",
      "3p": "λῡ́σουσι"
     },
     "aorist": {
      "1s": "ἔλῡσα",
      "2s": "ἔλῡσας",
      "3s": "ἔλῡσε",
      "2d": "ἐλῡ́σατον",
      "3d": "ἐλῡσάτην",
      "1p": "ἐλῡ́σαμεν",
      "2p": "ἐλῡ́σατε",
      "3p": "ἔλῡσαν"
     }
    },
    "middle_passive": {
     "present": {
      "1s": "λῡ́ομαι",
      "2s": [
       "λῡ́ῃ",
       "λῡ́ει"
      ],
      "3s": "λῡ́εται",
      "2d": "λῡ́εσθον",
      "3d": "λῡ́εσθον",
      "1p": "λῡόμεθα",
      "2p": "λῡ́εσθε",
      "3p": "λῡ́ονται"
     }
    }
   },
   {
    "lemma": "εἰμί",
    "smyth": 768,
    "gloss": "am",
    "note": "Present and future only (§768). The imperfect and the future indicative are included because that section gives them with the present, and there is no aorist to put in their place. Dissyllabic forms of the present indicative are enclitic; εἶ is not (§181 c). ἐστί is written ἔστι at the beginning of a sentence, when it means exists or is possible, and after οὐκ, μή, εἰ, ὡς, καί, ἀλλά, and τοῦτο (§187 b). Imperfect second person plural ἦτε, or ἦστε, which is rare.",
    "active": {
     "present": {
      "1s": "εἰμί",
      "2s": "εἶ",
      "3s": "ἐστί",
      "2d": "ἐστόν",
      "3d": "ἐστόν",
      "1p": "ἐσμέν",
      "2p": "ἐστέ",
      "3p": "εἰσί"
     },
     "imperfect": {
      "1s": [
       "ἦ",
       "ἦν"
      ],
      "2s": "ἦσθα",
      "3s": "ἦν",
      "2d": "ἤστον",
      "3d": "ἤστην",
      "1p": "ἦμεν",
      "2p": [
       "ἦτε",
       "ἦστε"
      ],
      "3p": "ἦσαν"
     }
    },
    "future_middle_form": {
     "1s": "ἔσομαι",
     "2s": [
      "ἔσῃ",
      "ἔσει"
     ],
     "3s": "ἔσται",
     "2d": "ἔσεσθον",
     "3d": "ἔσεσθον",
     "1p": "ἐσόμεθα",
     "2p": "ἔσεσθε",
     "3p": "ἔσονται"
    }
   }
  ]
 },
 "cards": {
  "title": "Greek beside Latin",
  "description": "What Attic Greek has, and where it differs from Latin.",
  "cards": [
   {
    "heading": "Attic Greek",
    "text": "We set Attic Greek beside Latin. The forms here are the forms of classical Athens. We do not use Homer's forms here."
   },
   {
    "heading": "Breathings",
    "text": "A word that begins with a vowel takes a breathing. The rough breathing is the sound of h, as in ὁ. The smooth breathing marks that the word does not begin with h, as in ἐστί. A word that begins with ρ also takes the rough breathing. Latin writes neither mark."
   },
   {
    "heading": "Accent",
    "text": "Greek writes the accent on the word. The acute, the grave, and the circumflex mark the pitch of a syllable, and the circumflex stands only on a long vowel or a diphthong. When another word follows, we write a grave for an acute on the last syllable, as in τὸν ἄνθρωπον. A word with the acute on its last syllable keeps that acute when an enclitic follows, as in ἀγαθή ἐστι. Latin does not mark the accent of an ordinary word. We learn the accent with the form."
   },
   {
    "heading": "The article",
    "text": "Greek has a definite article, ὁ, ἡ, τό, the. Latin has none. The article stands with its noun and agrees with the noun in gender, number, and case. ὁ ἄνθρωπος means the man. ἄνθρωπος, with no article, is not the same phrase."
   },
   {
    "heading": "The forms of the article",
    "text": "In the singular the nominative is ὁ, ἡ, τό, the genitive is τοῦ, τῆς, τοῦ, the dative is τῷ, τῇ, τῷ, and the accusative is τόν, τήν, τό. In the plural the nominative is οἱ, αἱ, τά, the genitive is τῶν for all three genders, the dative is τοῖς, ταῖς, τοῖς, and the accusative is τούς, τᾱ́ς, τά. The article has no vocative. ὁ, ἡ, οἱ, and αἱ are proclitics, and they take no accent."
   },
   {
    "heading": "The five cases",
    "text": "Greek has five cases: the nominative, the genitive, the dative, the accusative, and the vocative. The older names are ὀνομαστική, γενική, δοτική, αἰτιατική, and κλητική."
   },
   {
    "heading": "No ablative",
    "text": "Greek has no ablative. Where Latin uses the ablative, Greek uses the genitive or the dative. A Latin preposition takes the accusative or the ablative. A Greek preposition takes the genitive, the dative, or the accusative, and some prepositions take more than one of those cases. ἐν, in, takes the dative, as in ἐν τῇ χώρᾳ, in the land. ἐκ, out of, and ἀπό, from, take the genitive, as in ἐκ τῆς πόλεως, out of the city."
   },
   {
    "heading": "The vocative",
    "text": "The vocative is the case of address. ὦ κριτά addresses the judge, and κριτά is not the nominative κριτής. ὦ φύλαξ uses the same form as the nominative."
   },
   {
    "heading": "The dual",
    "text": "Greek has three numbers, the singular, the dual, and the plural. The dual is the number for two. Latin has no dual in the noun or in the verb. The dual of the article is τώ in the nominative and the accusative, and τοῖν in the genitive and the dative, for all three genders. The feminine dual forms τᾱ́ and ταῖν are very rare in the authors, and they are unknown on Attic prose inscriptions. The dual is uncommon in Attic prose."
   },
   {
    "heading": "Nouns",
    "text": "We list a noun by the nominative, the genitive singular, and the gender. χώρᾱ, χώρᾱς, feminine, means land, and the genitive shows the stem. Greek, like Latin, groups nouns in declensions. The nouns here are of the first, the second, and the third, and the endings are not the Latin endings. Attic writes θάλαττα, with ττ, for the sea."
   },
   {
    "heading": "Gender",
    "text": "Every noun has gender, masculine, feminine, or neuter, as in Latin. The article shows the gender. ὁ ἵππος is masculine, ἡ ὁδός is feminine, and τὸ δῶρον is neuter. ὁδός ends in ος, but it is feminine, so the article is ἡ. The ending does not always show the gender."
   },
   {
    "heading": "Adjectives",
    "text": "An adjective agrees with its noun in gender, number, and case. ἀγαθὸς ἄνθρωπος is a good man, ἀγαθὴ νῑ́κη is a good victory, and ἀγαθὸν δῶρον is a good gift. ἀληθής, true, has one form for the masculine and the feminine, and the neuter is ἀληθές."
   },
   {
    "heading": "Person and number",
    "text": "The ending of the verb shows the person and the number of the subject. The subject of παιδεύω is I. The subject of παιδεύει is he, she, or it. The subject of παιδεύουσι is they. The noun that is the subject of the verb stands in the nominative, as in ὁ ἄνθρωπος παιδεύει."
   },
   {
    "heading": "Present, imperfect, and future",
    "text": "The present indicative says that the action goes on now. παιδεύει means he educates. The imperfect says that it went on in the past. ἐπαίδευε means he was educating. The future says that it will happen. παιδεύσει means he will educate. The imperfect takes the augment, which is ἐ before a consonant."
   },
   {
    "heading": "The aorist",
    "text": "The aorist (ἀόριστος) is the simple past. ἐπαίδευσε means he educated. The aorist does not by itself say that the action went on, which is what the imperfect says, or that a result is still on hand, which is what the perfect says. Latin has no aorist of its own. For a simple past, Latin uses the perfect. The aorist, like the imperfect, takes the augment."
   },
   {
    "heading": "The middle",
    "text": "Greek has a middle voice beside the active and the passive. In the middle voice the subject acts on itself or for itself. παύει means he stops someone else, and παύεται means he ceases. λῡ́ει means he looses someone else, and λῡ́εται means he ransoms him. Latin has no middle voice."
   },
   {
    "heading": "Middle and passive forms",
    "text": "In the present, the imperfect, the perfect, and the pluperfect, the passive uses the middle forms. παύεται can mean he ceases, or he is stopped, and the rest of the sentence shows which is meant. The future passive and the aorist passive have forms of their own. In λῡ́ομαι the second person singular is λῡ́ῃ or λῡ́ει."
   },
   {
    "heading": "εἰμί",
    "text": "εἰμί means am, as Latin sum does. It has a present, an imperfect, ἦ or ἦν, and a future, ἔσομαι, I shall be, and the future is middle in form. Attic εἰμί has no aorist. The dissyllabic forms of the present indicative are enclitic, and εἶ is not. ἐστί is written ἔστι at the start of a sentence, when it means exists or is possible, and after οὐκ, μή, εἰ, ὡς, καί, ἀλλά, and τοῦτο."
   },
   {
    "heading": "Particles",
    "text": "Greek has particles, small words that are not inflected and that show how one clause stands to another. Some particles are conjunctions. καί means and, ἀλλά means but, γάρ means for, and οὖν means therefore. μέν and δέ mark the two sides of a pair. Latin does not have μέν and δέ."
   },
   {
    "heading": "Principal parts",
    "text": "We list a regular verb by six principal parts, the first person singular of the present, the future, the aorist, the perfect active, the perfect middle, and the aorist passive. λῡ́ω, loose, has the parts λῡ́σω, ἔλῡσα, λέλυκα, λέλυμαι, ἐλύθην. From those parts we build the other forms. εἰμί does not have this set of six."
   },
   {
    "heading": "The object",
    "text": "The direct object of a verb stands in the accusative. In παιδεύει τὸν ἄνθρωπον, he educates the man, τὸν ἄνθρωπον is the object of παιδεύει. Some verbs take the genitive or the dative, and then that case belongs to the meaning of the verb."
   },
   {
    "heading": "Movable nu",
    "text": "Some forms may take a ν at the end, above all before a vowel. ἐστί and ἐστίν are one form, and so are the third person plural in σι and the dative plural in σι. Movable ν also comes on third-person singulars in -ε, such as ἔλῡσε(ν). The added ν does not change the case, the person, or the number."
   },
   {
    "heading": "The hexameter",
    "text": "The dactylic hexameter is a line of six feet. A foot is a dactyl, one long syllable and two short syllables, or a spondee, two long syllables. Homer uses this meter, and so do Virgil and Ovid. Homer's Greek is older than Attic, and a form that fits the meter in Homer is not, for that reason, the Attic form."
   },
   {
    "heading": "Stem and ending",
    "text": "The form in the sentence is a stem and an ending. In νῑ́κης the ending -ς marks the genitive singular. In παιδεύομεν the ending -ομεν marks the first person plural, and the subject of the verb is we. The ending marks the case, the person, or the number."
   },
   {
    "heading": "The macron",
    "text": "A macron over α, ι, or υ marks the vowel as long. Smyth prints it so that the quantity is visible, and these paradigms keep his marks. The macron is a teaching mark, and ancient writing did not use it. The accent and the breathing belong to the traditional text. They were not written in classical Attic."
   }
  ]
 },
 "items": {
  "language": "grc",
  "dialect": "Attic",
  "source": "One blank in each Greek frame. The answer is the form that belongs in the sentence, including a grave where §154 requires it and the enclitic accent of §183. Wrong forms are real forms that do not fit the frame.",
  "items": [
   {
    "id": "art-1",
    "kind": "article",
    "en": "The man educates the horse.",
    "frame": "______ ἄνθρωπος παιδεύει τὸν ἵππον.",
    "answer": "ὁ",
    "wrong": [
     "ἡ",
     "τὸ",
     "οἱ"
    ]
   },
   {
    "id": "art-2",
    "kind": "article",
    "en": "The victory is good.",
    "frame": "______ νῑ́κη ἀγαθή ἐστι.",
    "answer": "ἡ",
    "wrong": [
     "ὁ",
     "τὸ",
     "αἱ"
    ]
   },
   {
    "id": "art-3",
    "kind": "article",
    "en": "The gift is good.",
    "frame": "______ δῶρον ἀγαθόν ἐστι.",
    "answer": "τὸ",
    "wrong": [
     "ὁ",
     "ἡ",
     "τὰ"
    ]
   },
   {
    "id": "art-4",
    "kind": "article",
    "en": "The judges educate the young man.",
    "frame": "οἱ κριταὶ παιδεύουσι ______ νεᾱνίᾱν.",
    "answer": "τὸν",
    "wrong": [
     "ὁ",
     "τὴν",
     "τοὺς"
    ]
   },
   {
    "id": "art-5",
    "kind": "article",
    "en": "The hope of the judges is good.",
    "frame": "ἡ ἐλπὶς ______ κριτῶν ἀγαθή ἐστι.",
    "answer": "τῶν",
    "wrong": [
     "τὸν",
     "τὰ",
     "τοὺς"
    ]
   },
   {
    "id": "art-6",
    "kind": "article",
    "en": "He writes in the land.",
    "frame": "γράφει ἐν ______ χώρᾳ.",
    "answer": "τῇ",
    "wrong": [
     "τὴν",
     "τῆς",
     "τὸ"
    ]
   },
   {
    "id": "art-7",
    "kind": "article",
    "en": "They send the gifts.",
    "frame": "πέμπουσι ______ δῶρα.",
    "answer": "τὰ",
    "wrong": [
     "τὸ",
     "τοὺς",
     "τᾱ̀ς"
    ]
   },
   {
    "id": "art-8",
    "kind": "article",
    "en": "The horses of the king are good.",
    "frame": "οἱ ἵπποι ______ βασιλέως ἀγαθοί εἰσι.",
    "answer": "τοῦ",
    "wrong": [
     "τὸν",
     "τῷ",
     "τῶν"
    ]
   },
   {
    "id": "case-1",
    "kind": "case",
    "en": "He educates the man.",
    "frame": "παιδεύει τὸν ______.",
    "answer": "ἄνθρωπον",
    "wrong": [
     "ἄνθρωπος",
     "ἀνθρώπου",
     "ἀνθρώπῳ"
    ]
   },
   {
    "id": "case-2",
    "kind": "case",
    "en": "They loose the horse.",
    "frame": "λῡ́ουσι τὸν ______.",
    "answer": "ἵππον",
    "wrong": [
     "ἵππος",
     "ἵππου",
     "ἵππῳ"
    ]
   },
   {
    "id": "case-3",
    "kind": "case",
    "en": "He sends the gift.",
    "frame": "πέμπει τὸ ______.",
    "answer": "δῶρον",
    "wrong": [
     "δῶρα",
     "δώρου",
     "δώρῳ"
    ]
   },
   {
    "id": "case-4",
    "kind": "case",
    "en": "The gift is in the land.",
    "frame": "τὸ δῶρον ἐν τῇ ______ ἐστί.",
    "answer": "χώρᾳ",
    "wrong": [
     "χώραις",
     "χώρᾱς",
     "χώρᾱν"
    ]
   },
   {
    "id": "case-5",
    "kind": "case",
    "en": "He sends the man out of the city.",
    "frame": "πέμπει τὸν ἄνθρωπον ἐκ τῆς ______.",
    "answer": "πόλεως",
    "wrong": [
     "πόλιν",
     "πόλει",
     "πόλεις"
    ]
   },
   {
    "id": "case-6",
    "kind": "case",
    "en": "They dance with the king.",
    "frame": "χορεύουσι σὺν τῷ ______.",
    "answer": "βασιλεῖ",
    "wrong": [
     "βασιλεύς",
     "βασιλέως",
     "βασιλέᾱ"
    ]
   },
   {
    "id": "case-7",
    "kind": "case",
    "en": "He stops the judge.",
    "frame": "παύει τὸν ______.",
    "answer": "κριτήν",
    "wrong": [
     "κριτής",
     "κριτοῦ",
     "κριτῇ"
    ]
   },
   {
    "id": "case-8",
    "kind": "case",
    "en": "The men are far from the sea.",
    "frame": "οἱ ἄνθρωποί εἰσιν ἀπὸ τῆς ______.",
    "answer": "θαλάττης",
    "wrong": [
     "θάλαττα",
     "θάλατταν",
     "θαλάττῃ"
    ]
   },
   {
    "id": "pers-1",
    "kind": "person",
    "en": "I educate the man.",
    "frame": "τὸν ἄνθρωπον ______.",
    "answer": "παιδεύω",
    "wrong": [
     "παιδεύεις",
     "παιδεύει",
     "παιδεύομεν"
    ]
   },
   {
    "id": "pers-2",
    "kind": "person",
    "en": "You educate the man.",
    "frame": "τὸν ἄνθρωπον ______.",
    "answer": "παιδεύεις",
    "wrong": [
     "παιδεύω",
     "παιδεύει",
     "παιδεύετε"
    ]
   },
   {
    "id": "pers-3",
    "kind": "person",
    "en": "The man educates the horse.",
    "frame": "ὁ ἄνθρωπος τὸν ἵππον ______.",
    "answer": "παιδεύει",
    "wrong": [
     "παιδεύω",
     "παιδεύουσι",
     "παιδεύομεν"
    ]
   },
   {
    "id": "pers-4",
    "kind": "person",
    "en": "We educate the young man.",
    "frame": "τὸν νεᾱνίᾱν ______.",
    "answer": "παιδεύομεν",
    "wrong": [
     "παιδεύω",
     "παιδεύετε",
     "παιδεύουσι"
    ]
   },
   {
    "id": "pers-5",
    "kind": "person",
    "en": "All of you loose the horse.",
    "frame": "τὸν ἵππον ______.",
    "answer": "λῡ́ετε",
    "wrong": [
     "λῡ́ω",
     "λῡ́ει",
     "λῡ́ουσι"
    ]
   },
   {
    "id": "pers-6",
    "kind": "person",
    "en": "The judges loose the man.",
    "frame": "οἱ κριταὶ τὸν ἄνθρωπον ______.",
    "answer": "λῡ́ουσι",
    "wrong": [
     "λῡ́ει",
     "λῡ́ομεν",
     "λῡ́εις"
    ]
   },
   {
    "id": "pers-7",
    "kind": "person",
    "en": "I am a young man.",
    "frame": "νεᾱνίᾱς ______.",
    "answer": "εἰμί",
    "wrong": [
     "εἶ",
     "ἐστί",
     "ἐσμέν"
    ]
   },
   {
    "id": "pers-8",
    "kind": "person",
    "en": "You are a young man.",
    "frame": "νεᾱνίᾱς ______.",
    "answer": "εἶ",
    "wrong": [
     "εἰμί",
     "ἐστί",
     "εἰσί"
    ]
   },
   {
    "id": "aor-1",
    "kind": "aorist",
    "en": "He educated the man.",
    "frame": "τὸν ἄνθρωπον ______.",
    "answer": "ἐπαίδευσε",
    "wrong": [
     "παιδεύει",
     "ἐπαίδευε",
     "παιδεύσει"
    ]
   },
   {
    "id": "aor-2",
    "kind": "aorist",
    "en": "They loosed the horse.",
    "frame": "τὸν ἵππον ______.",
    "answer": "ἔλῡσαν",
    "wrong": [
     "λῡ́ουσι",
     "ἔλῡον",
     "λῡ́σουσι"
    ]
   },
   {
    "id": "aor-3",
    "kind": "aorist",
    "en": "I educated the judge.",
    "frame": "τὸν κριτὴν ______.",
    "answer": "ἐπαίδευσα",
    "wrong": [
     "παιδεύω",
     "ἐπαίδευον",
     "παιδεύσω"
    ]
   },
   {
    "id": "aor-4",
    "kind": "aorist",
    "en": "We loosed the gifts.",
    "frame": "τὰ δῶρα ______.",
    "answer": "ἐλῡ́σαμεν",
    "wrong": [
     "λῡ́ομεν",
     "ἐλῡ́ομεν",
     "λῡ́σομεν"
    ]
   },
   {
    "id": "aor-5",
    "kind": "aorist",
    "en": "The king sacrificed.",
    "frame": "ὁ βασιλεὺς ______.",
    "answer": "ἔθῡσε",
    "wrong": [
     "θῡ́ει",
     "ἔθῡε",
     "θῡ́σει"
    ]
   },
   {
    "id": "aor-6",
    "kind": "aorist",
    "en": "She stopped the horse.",
    "frame": "τὸν ἵππον ______.",
    "answer": "ἔπαυσε",
    "wrong": [
     "παύει",
     "ἔπαυε",
     "παύσει"
    ]
   },
   {
    "id": "aor-7",
    "kind": "aorist",
    "en": "The judges danced.",
    "frame": "οἱ κριταὶ ______.",
    "answer": "ἐχόρευσαν",
    "wrong": [
     "χορεύουσι",
     "ἐχόρευον",
     "χορεύσουσι"
    ]
   },
   {
    "id": "aor-8",
    "kind": "aorist",
    "en": "We educated the king.",
    "frame": "τὸν βασιλέᾱ ______.",
    "answer": "ἐπαιδεύσαμεν",
    "wrong": [
     "παιδεύομεν",
     "ἐπαιδεύομεν",
     "παιδεύσομεν"
    ]
   },
   {
    "id": "mid-1",
    "kind": "middle",
    "en": "The man ceases.",
    "frame": "ὁ ἄνθρωπος ______.",
    "answer": "παύεται",
    "wrong": [
     "παύει",
     "ἐπαύετο",
     "παύονται"
    ]
   },
   {
    "id": "mid-2",
    "kind": "middle",
    "en": "The men cease.",
    "frame": "οἱ ἄνθρωποι ______.",
    "answer": "παύονται",
    "wrong": [
     "παύουσι",
     "παύεται",
     "ἐπαύοντο"
    ]
   },
   {
    "id": "mid-3",
    "kind": "middle",
    "en": "I ransom the man.",
    "frame": "τὸν ἄνθρωπον ______.",
    "answer": "λῡ́ομαι",
    "wrong": [
     "λῡ́ω",
     "λῡ́σομαι",
     "ἐλῡόμην"
    ]
   },
   {
    "id": "mid-4",
    "kind": "middle",
    "en": "We ransom the judge.",
    "frame": "τὸν κριτὴν ______.",
    "answer": "λῡόμεθα",
    "wrong": [
     "λῡ́ομεν",
     "λῡ́εσθε",
     "ἐλῡόμεθα"
    ]
   },
   {
    "id": "mid-5",
    "kind": "middle",
    "en": "He ransoms the horse.",
    "frame": "τὸν ἵππον ______.",
    "answer": "λῡ́εται",
    "wrong": [
     "λῡ́ει",
     "λῡ́σεται",
     "ἐλῡ́ετο"
    ]
   },
   {
    "id": "mid-6",
    "kind": "middle",
    "en": "I ransomed the man.",
    "frame": "τὸν ἄνθρωπον ______.",
    "answer": "ἐλῡσάμην",
    "wrong": [
     "ἔλῡσα",
     "ἐλῡσάμεθα",
     "λῡ́ομαι"
    ]
   },
   {
    "id": "mid-7",
    "kind": "middle",
    "en": "They ransomed the judge.",
    "frame": "τὸν κριτὴν ______.",
    "answer": "ἐλῡ́σαντο",
    "wrong": [
     "ἔλῡσαν",
     "ἐλῡσάμεθα",
     "λῡ́ονται"
    ]
   },
   {
    "id": "mid-8",
    "kind": "middle",
    "en": "All of you get the judges set free.",
    "frame": "τοὺς κριτᾱ̀ς ______.",
    "answer": "λῡ́εσθε",
    "wrong": [
     "λῡ́ετε",
     "λῡ́ονται",
     "ἐλῡ́εσθε"
    ]
   }
  ]
 }
};
