#!/usr/bin/env node
/**
 * build_greek.js: read the four Greek JSON files in this folder and write greek.js at the repository
 * root. greek.js defines one global, window.GREEK = {vocab, paradigms, cards, items}, with every
 * string exactly as it stands in the JSON. Run from the repository root:
 *   node greek/build_greek.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const here = __dirname;
const out = path.join(here, '..', 'greek.js');
const read = name => JSON.parse(fs.readFileSync(path.join(here, 'greek-' + name + '.json'), 'utf8'));
const GREEK = { vocab: read('vocab'), paradigms: read('paradigms'), cards: read('cards'), items: read('items') };

/* Every string must already be in Unicode NFC. Nothing here normalizes or rewrites a form. */
const problems = [];
(function walk(o, at){
  if(typeof o === 'string'){ if(o !== o.normalize('NFC')) problems.push(at + ' is not NFC: ' + o); return; }
  if(o && typeof o === 'object') for(const k of Object.keys(o)) walk(o[k], at + '.' + k);
})(GREEK, 'GREEK');

if(problems.length){
  console.error(problems.join('\n'));
  process.exit(1);
}
fs.writeFileSync(out,
  '/* Generated by greek/build_greek.js from the JSON files in greek/. Do not edit by hand. */\n'
  + 'window.GREEK = ' + JSON.stringify(GREEK, null, 1) + ';\n');
console.log('Wrote ' + out);
