#!/usr/bin/env node
/**
 * build_greek.js: read the four Greek JSON files in this folder and write greek.js at the repository
 * root. greek.js defines one global, window.GREEK = {vocab, paradigms, cards, items}, with every
 * string exactly as it stands in the JSON. Run from the repository root:
 *   node greek/build_greek.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const here = __dirname;
const out = path.join(here, '..', 'greek.js');
const read = name => JSON.parse(fs.readFileSync(path.join(here, 'greek-' + name + '.json'), 'utf8'));
const GREEK = { vocab: read('vocab'), paradigms: read('paradigms'), cards: read('cards'), items: read('items') };

/* Every string must already be in Unicode NFC. Nothing here normalizes or rewrites a form. */
const problems = [];
(function walk(o, at){
  if(typeof o === 'string'){ if(o !== o.normalize('NFC')) problems.push(at + ' is not NFC: ' + o); return; }
  if(o && typeof o === 'object') for(const k of Object.keys(o)) walk(o[k], at + '.' + k);
})(GREEK, 'GREEK');

/* Grading safety. The exercise compares typed Greek without accents, breathings, iota subscript, macrons, or
   case, and reads plain Latin letters as Greek. This is the same comparison as normGrk in index.html. Under it,
   no wrong option may match the answer, whether it is typed in Greek or in Latin letters, and the answer
   typed in Latin letters must match the answer. */
const BETA = {a:'α', b:'β', g:'γ', d:'δ', e:'ε', z:'ζ', h:'η', q:'θ', i:'ι', k:'κ', l:'λ', m:'μ', n:'ν',
  c:'ξ', o:'ο', p:'π', r:'ρ', s:'σ', t:'τ', u:'υ', f:'φ', x:'χ', y:'ψ', w:'ω'};
const TO_LATIN = Object.fromEntries(Object.entries(BETA).map(([k, v]) => [v, k]));
function normGrk(s){
  return String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[a-z]/g, c => BETA[c]).replace(/ς/g, 'σ').replace(/[^\u0370-\u03ff]/g, '');
}
function asLatin(s){
  return normGrk(s).split('').map(c => {
    if(!TO_LATIN[c]) problems.push('No Latin letter for ' + c + ' in ' + s);
    return TO_LATIN[c] || '';
  }).join('');
}
GREEK.items.items.forEach(it => {
  const a = normGrk(it.answer), aLat = normGrk(asLatin(it.answer));
  if(!a) problems.push(it.id + ': the answer is empty after normalizing');
  if(aLat !== a) problems.push(it.id + ': the answer typed in Latin letters does not match the answer');
  it.wrong.forEach(w => {
    if(normGrk(w) === a) problems.push(it.id + ': the wrong option ' + w + ' matches the answer ' + it.answer + ' in Greek');
    if(normGrk(asLatin(w)) === aLat) problems.push(it.id + ': the wrong option ' + w + ' matches the answer ' + it.answer + ' in Latin letters');
  });
});

if(problems.length){
  console.error(problems.join('\n'));
  process.exit(1);
}
fs.writeFileSync(out,
  '/* Generated by greek/build_greek.js from the JSON files in greek/. Do not edit by hand. */\n'
  + 'window.GREEK = ' + JSON.stringify(GREEK, null, 1) + ';\n');
console.log('Grading safety: ' + GREEK.items.items.length + ' items, no wrong option matches its answer.');
console.log('Wrote ' + out);
